Shader "SR/Actor/Recolor x8 Vertex Color" {
	Properties {
		[NoScaleOffset] _ColorMask ("Color Mask", 2D) = "black" {}
		[NoScaleOffset] _Rim ("Rim", 2D) = "black" {}
		_RimStrength ("Rim Strength", Range(0, 1)) = 1
		_Color00 ("Color 00", Color) = (0.5019608,0,0,0)
		_Color01 ("Color 01", Color) = (1,0,0,0)
		_Color20 ("Color 20", Color) = (0,0,0.5,0)
		_Color21 ("Color 21", Color) = (0,0,1,0)
		_Color10 ("Color 10", Color) = (0,0.5,0,0)
		_Color11 ("Color 11", Color) = (0,1,0,0)
		_Color30 ("Color 30", Color) = (0,0,0,0)
		_Color31 ("Color 31", Color) = (0.3,0.3,0.3,0)
		_Color40 ("Color 40", Color) = (0.5,0,0.5,0)
		_Color41 ("Color 41", Color) = (1,0,1,0)
		_Color50 ("Color 50", Color) = (0.5,0.5,0,0)
		_Color51 ("Color 51", Color) = (1,1,0,0)
		_Color60 ("Color 60", Color) = (0,0.5,0.5,0)
		_Color61 ("Color 61", Color) = (0,1,1,0)
		_Color70 ("Color 70", Color) = (0.5,0.5,0.5,0)
		_Color71 ("Color 71", Color) = (1,1,1,0)
		[NoScaleOffset] _GlowRamp ("Ramp Alpha (Glow)", 2D) = "black" {}
		_SpiralColor ("Glow Shift", Range(0, 1)) = 0
		_Normal ("Normal", 2D) = "bump" {}
		[MaterialToggle] _NRMUV1 ("NRM UV 1", Float) = 0
		[MaterialToggle] _NRMTriplanar ("NRM Triplanar", Float) = 0
		_PaintStrokes ("PaintStrokes", 2D) = "gray" {}
		[MaterialToggle] _PaintMaskTriplanar ("PaintMask Triplanar", Float) = 0
		_GlowMultiplier ("Glow Multiplier", Float) = 1
		_GlowSpeed ("Glow Speed", Float) = 0
	}
	SubShader {
		Tags { "PreviewType" = "Plane" "RenderType" = "Opaque" }
		Pass {
			Name "FORWARD"
			Tags { "LIGHTMODE" = "FORWARDBASE" "PreviewType" = "Plane" "RenderType" = "Opaque" "SHADOWSUPPORT" = "true" }
			GpuProgramID 22672
			CGPROGRAM
			#pragma vertex vert
			#pragma fragment frag
			
			#include "UnityCG.cginc"
			struct v2f
			{
				float4 position : SV_POSITION0;
				float2 texcoord : TEXCOORD0;
				float2 texcoord1 : TEXCOORD1;
				float4 texcoord2 : TEXCOORD2;
				float3 texcoord3 : TEXCOORD3;
				float3 texcoord4 : TEXCOORD4;
				float3 texcoord5 : TEXCOORD5;
				float4 color : COLOR0;
			};
			struct fout
			{
				float4 sv_target : SV_Target0;
			};
			// $Globals ConstantBuffers for Vertex Shader
			// $Globals ConstantBuffers for Fragment Shader
			float4 _LightColor0;
			float _RimStrength;
			float4 _Color01;
			float4 _Color21;
			float4 _Color11;
			float4 _Color31;
			float4 _Color00;
			float4 _Color10;
			float4 _Color20;
			float4 _Color30;
			float _SpiralColor;
			float4 _Color41;
			float4 _Color51;
			float4 _Color61;
			float4 _Color71;
			float4 _Color40;
			float4 _Color50;
			float4 _Color60;
			float4 _Color70;
			float4 _Normal_ST;
			float _NRMUV1;
			float _NRMTriplanar;
			float4 _PaintStrokes_ST;
			float _PaintMaskTriplanar;
			float _GlowMultiplier;
			float _GlowSpeed;
			// Custom ConstantBuffers for Vertex Shader
			// Custom ConstantBuffers for Fragment Shader
			// Texture params for Vertex Shader
			// Texture params for Fragment Shader
			sampler2D _Normal;
			sampler2D _ColorMask;
			sampler2D _PaintStrokes;
			sampler2D _GlowRamp;
			sampler2D _Rim;
			
			// Keywords: DIRECTIONAL
			v2f vert(appdata_full v)
			{
                v2f o;
                float4 tmp0;
                float4 tmp1;
                float4 tmp2;
                tmp0 = v.vertex.yyyy * unity_ObjectToWorld._m01_m11_m21_m31;
                tmp0 = unity_ObjectToWorld._m00_m10_m20_m30 * v.vertex.xxxx + tmp0;
                tmp0 = unity_ObjectToWorld._m02_m12_m22_m32 * v.vertex.zzzz + tmp0;
                tmp1 = tmp0 + unity_ObjectToWorld._m03_m13_m23_m33;
                o.texcoord2 = unity_ObjectToWorld._m03_m13_m23_m33 * v.vertex.wwww + tmp0;
                tmp0 = tmp1.yyyy * unity_MatrixVP._m01_m11_m21_m31;
                tmp0 = unity_MatrixVP._m00_m10_m20_m30 * tmp1.xxxx + tmp0;
                tmp0 = unity_MatrixVP._m02_m12_m22_m32 * tmp1.zzzz + tmp0;
                o.position = unity_MatrixVP._m03_m13_m23_m33 * tmp1.wwww + tmp0;
                o.texcoord.xy = v.texcoord.xy;
                o.texcoord1.xy = v.texcoord1.xy;
                tmp0.x = dot(v.normal.xyz, unity_WorldToObject._m00_m10_m20);
                tmp0.y = dot(v.normal.xyz, unity_WorldToObject._m01_m11_m21);
                tmp0.z = dot(v.normal.xyz, unity_WorldToObject._m02_m12_m22);
                tmp0.w = dot(tmp0.xyz, tmp0.xyz);
                tmp0.w = rsqrt(tmp0.w);
                tmp0.xyz = tmp0.www * tmp0.xyz;
                o.texcoord3.xyz = tmp0.xyz;
                tmp1.xyz = v.tangent.yyy * unity_ObjectToWorld._m01_m11_m21;
                tmp1.xyz = unity_ObjectToWorld._m00_m10_m20 * v.tangent.xxx + tmp1.xyz;
                tmp1.xyz = unity_ObjectToWorld._m02_m12_m22 * v.tangent.zzz + tmp1.xyz;
                tmp0.w = dot(tmp1.xyz, tmp1.xyz);
                tmp0.w = rsqrt(tmp0.w);
                tmp1.xyz = tmp0.www * tmp1.xyz;
                o.texcoord4.xyz = tmp1.xyz;
                tmp2.xyz = tmp0.zxy * tmp1.yzx;
                tmp0.xyz = tmp0.yzx * tmp1.zxy + -tmp2.xyz;
                tmp0.xyz = tmp0.xyz * v.tangent.www;
                tmp0.w = dot(tmp0.xyz, tmp0.xyz);
                tmp0.w = rsqrt(tmp0.w);
                o.texcoord5.xyz = tmp0.www * tmp0.xyz;
                o.color = v.color;
                return o;
			}
			// Keywords: DIRECTIONAL
			fout frag(v2f inp)
			{
                fout o;
                float4 tmp0;
                float4 tmp1;
                float4 tmp2;
                float4 tmp3;
                float4 tmp4;
                float4 tmp5;
                float4 tmp6;
                float4 tmp7;
                float4 tmp8;
                float4 tmp9;
                float4 tmp10;
                tmp0.xy = inp.texcoord2.zx * _PaintStrokes_ST.xy + _PaintStrokes_ST.zw;
                tmp0 = tex2D(_PaintStrokes, tmp0.xy);
                tmp1 = inp.texcoord2.xyyz * _PaintStrokes_ST + _PaintStrokes_ST;
                tmp2 = tex2D(_PaintStrokes, tmp1.zw);
                tmp1 = tex2D(_PaintStrokes, tmp1.xy);
                tmp0.y = tmp2.x - tmp1.x;
                tmp0.z = dot(inp.texcoord3.xyz, inp.texcoord3.xyz);
                tmp0.z = rsqrt(tmp0.z);
                tmp1.yzw = tmp0.zzz * inp.texcoord3.xyz;
                tmp0.y = abs(tmp1.y) * tmp0.y + tmp1.x;
                tmp0.x = tmp0.x - tmp0.y;
                tmp0.x = abs(tmp1.z) * tmp0.x + tmp0.y;
                tmp0.y = tmp1.x - tmp0.x;
                tmp0.x = abs(tmp1.w) * tmp0.y + tmp0.x;
                tmp2.xy = inp.texcoord2.zx * _PaintStrokes_ST.xy;
                tmp3 = tmp2.xyxy * float4(0.9, 0.9, 1.1, 1.1) + _PaintStrokes_ST;
                tmp2.xy = tmp2.xy * float2(0.65, 0.65) + _PaintStrokes_ST.zw;
                tmp2 = tex2D(_PaintStrokes, tmp2.xy);
                tmp4 = tex2D(_PaintStrokes, tmp3.xy);
                tmp3 = tex2D(_PaintStrokes, tmp3.zw);
                tmp5 = inp.texcoord2.xyyz * _PaintStrokes_ST;
                tmp6 = tmp5 * float4(0.9, 0.9, 0.9, 0.9) + _PaintStrokes_ST;
                tmp7 = tex2D(_PaintStrokes, tmp6.zw);
                tmp6 = tex2D(_PaintStrokes, tmp6.xy);
                tmp0.w = tmp7.y - tmp6.y;
                tmp0.w = abs(tmp1.y) * tmp0.w + tmp6.y;
                tmp1.x = tmp4.y - tmp0.w;
                tmp0.w = abs(tmp1.z) * tmp1.x + tmp0.w;
                tmp1.x = tmp6.y - tmp0.w;
                tmp0.y = abs(tmp1.w) * tmp1.x + tmp0.w;
                tmp4 = tmp5 * float4(1.1, 1.1, 1.1, 1.1) + _PaintStrokes_ST;
                tmp5 = tmp5 * float4(0.55, 0.55, 0.45, 0.45) + _PaintStrokes_ST;
                tmp6 = tex2D(_PaintStrokes, tmp4.zw);
                tmp4 = tex2D(_PaintStrokes, tmp4.xy);
                tmp0.w = tmp6.y - tmp4.y;
                tmp0.w = abs(tmp1.y) * tmp0.w + tmp4.y;
                tmp1.x = tmp3.y - tmp0.w;
                tmp0.w = abs(tmp1.z) * tmp1.x + tmp0.w;
                tmp1.x = tmp4.y - tmp0.w;
                tmp0.z = abs(tmp1.w) * tmp1.x + tmp0.w;
                tmp3.xyz = float3(1.0, 1.0, 1.0) - tmp0.xyz;
                tmp4 = tex2D(_PaintStrokes, tmp5.zw);
                tmp5 = tex2D(_PaintStrokes, tmp5.xy);
                tmp4.xyz = tmp4.xyz - tmp5.xyz;
                tmp4.xyz = abs(tmp1.yyy) * tmp4.xyz + tmp5.xyz;
                tmp2.xyz = tmp2.xyz - tmp4.xyz;
                tmp2.xyz = abs(tmp1.zzz) * tmp2.xyz + tmp4.xyz;
                tmp4.xyz = tmp5.xyz - tmp2.xyz;
                tmp2.xyz = abs(tmp1.www) * tmp4.xyz + tmp2.xyz;
                tmp4.xyz = tmp2.xyz - float3(0.5, 0.5, 0.5);
                tmp4.xyz = -tmp4.xyz * float3(2.0, 2.0, 2.0) + float3(1.0, 1.0, 1.0);
                tmp3.xyz = -tmp4.xyz * tmp3.xyz + float3(1.0, 1.0, 1.0);
                tmp0.xyz = tmp0.xyz * tmp2.xyz;
                tmp2.xyz = tmp2.xyz > float3(0.5, 0.5, 0.5);
                tmp0.xyz = tmp0.xyz + tmp0.xyz;
                tmp0.xyz = saturate(tmp2.xyz ? tmp3.xyz : tmp0.xyz);
                tmp2.xy = inp.texcoord1.xy - inp.texcoord.xy;
                tmp2.xy = _NRMUV1.xx * tmp2.xy + inp.texcoord.xy;
                tmp2.zw = tmp2.xy * _PaintStrokes_ST.xy + _PaintStrokes_ST.zw;
                tmp2.xy = tmp2.xy * _Normal_ST.xy + _Normal_ST.zw;
                tmp3 = tex2D(_Normal, tmp2.xy);
                tmp2 = tex2D(_PaintStrokes, tmp2.zw);
                tmp0.xyz = tmp0.xyz - tmp2.xyz;
                tmp0.xyz = _PaintMaskTriplanar.xxx * tmp0.xyz + tmp2.xyz;
                tmp2.xy = tmp0.xz * float2(0.3, 0.2) + float2(0.35, 0.4);
                tmp0.xyz = tmp0.xyz - float3(0.5, 0.5, 0.5);
                tmp2.zw = inp.texcoord2.zx * _Normal_ST.xy + _Normal_ST.zw;
                tmp4 = tex2D(_Normal, tmp2.zw);
                tmp4.x = tmp4.w * tmp4.x;
                tmp4.xy = tmp4.xy * float2(2.0, 2.0) + float2(-1.0, -1.0);
                tmp0.w = dot(tmp4.xy, tmp4.xy);
                tmp0.w = min(tmp0.w, 1.0);
                tmp0.w = 1.0 - tmp0.w;
                tmp4.z = sqrt(tmp0.w);
                tmp5 = inp.texcoord2.xyyz * _Normal_ST + _Normal_ST;
                tmp6 = tex2D(_Normal, tmp5.zw);
                tmp5 = tex2D(_Normal, tmp5.xy);
                tmp6.x = tmp6.w * tmp6.x;
                tmp6.xy = tmp6.xy * float2(2.0, 2.0) + float2(-1.0, -1.0);
                tmp0.w = dot(tmp6.xy, tmp6.xy);
                tmp0.w = min(tmp0.w, 1.0);
                tmp0.w = 1.0 - tmp0.w;
                tmp6.z = sqrt(tmp0.w);
                tmp5.x = tmp5.w * tmp5.x;
                tmp5.xy = tmp5.xy * float2(2.0, 2.0) + float2(-1.0, -1.0);
                tmp0.w = dot(tmp5.xy, tmp5.xy);
                tmp0.w = min(tmp0.w, 1.0);
                tmp0.w = 1.0 - tmp0.w;
                tmp5.z = sqrt(tmp0.w);
                tmp6.xyz = tmp6.xyz - tmp5.xyz;
                tmp6.xyz = abs(tmp1.yyy) * tmp6.xyz + tmp5.xyz;
                tmp4.xyz = tmp4.xyz - tmp6.xyz;
                tmp4.xyz = abs(tmp1.zzz) * tmp4.xyz + tmp6.xyz;
                tmp5.xyz = tmp5.xyz - tmp4.xyz;
                tmp4.xyz = abs(tmp1.www) * tmp5.xyz + tmp4.xyz;
                tmp3.x = tmp3.w * tmp3.x;
                tmp3.xy = tmp3.xy * float2(2.0, 2.0) + float2(-1.0, -1.0);
                tmp0.w = dot(tmp3.xy, tmp3.xy);
                tmp0.w = min(tmp0.w, 1.0);
                tmp0.w = 1.0 - tmp0.w;
                tmp3.z = sqrt(tmp0.w);
                tmp4.xyz = tmp4.xyz - tmp3.xyz;
                tmp3.xyz = _NRMTriplanar.xxx * tmp4.xyz + tmp3.xyz;
                tmp4.xyz = tmp3.yyy * inp.texcoord5.xyz;
                tmp3.xyw = tmp3.xxx * inp.texcoord4.xyz + tmp4.xyz;
                tmp1.xyz = tmp3.zzz * tmp1.yzw + tmp3.xyw;
                tmp0.w = dot(tmp1.xyz, tmp1.xyz);
                tmp0.w = rsqrt(tmp0.w);
                tmp1.xyz = tmp0.www * tmp1.xyz;
                tmp3.xyz = _WorldSpaceCameraPos - inp.texcoord2.xyz;
                tmp0.w = dot(tmp3.xyz, tmp3.xyz);
                tmp0.w = rsqrt(tmp0.w);
                tmp4.xyz = tmp0.www * tmp3.xyz;
                tmp1.w = dot(tmp1.xyz, tmp4.xyz);
                tmp1.w = max(tmp1.w, 0.0);
                tmp1.w = 1.0 - tmp1.w;
                tmp1.w = log(tmp1.w);
                tmp4 = _Color00 - _Color30;
                tmp5 = tex2D(_ColorMask, inp.texcoord.xy);
                tmp4 = tmp5.xxxx * tmp4 + _Color30;
                tmp6 = _Color10 - tmp4;
                tmp4 = tmp5.yyyy * tmp6 + tmp4;
                tmp6 = _Color20 - tmp4;
                tmp4 = tmp5.zzzz * tmp6 + tmp4;
                tmp6 = _Color40 - tmp4;
                tmp7.xyz = saturate(tmp5.xyz * float3(1.49925, 1.49925, 1.49925) + float3(-0.4992504, -0.4992504, -0.4992504));
                tmp2.z = tmp7.y * tmp7.x;
                tmp2.z = tmp7.z * tmp2.z;
                tmp7.xyz = tmp7.xxy * tmp7.zyz + -tmp2.zzz;
                tmp4 = tmp7.xxxx * tmp6 + tmp4;
                tmp6 = _Color50 - tmp4;
                tmp4 = tmp7.yyyy * tmp6 + tmp4;
                tmp6 = _Color60 - tmp4;
                tmp4 = tmp7.zzzz * tmp6 + tmp4;
                tmp6 = _Color70 - tmp4;
                tmp4 = tmp2.zzzz * tmp6 + tmp4;
                tmp2.w = tmp4.x * 2.5 + 1.5;
                tmp1.w = tmp1.w * tmp2.w;
                tmp1.w = exp(tmp1.w);
                tmp1.w = tmp1.w * tmp1.w;
                tmp1.w = min(tmp1.w, 1.0);
                tmp2.w = dot(tmp2.xy, tmp1.xy);
                tmp6.xy = float2(1.0, 1.0) - tmp2.xy;
                tmp2.x = tmp1.w - 0.5;
                tmp1.w = tmp1.w > 0.5;
                tmp2.x = -tmp2.x * 2.0 + 1.0;
                tmp2.x = -tmp2.x * tmp6.x + 1.0;
                tmp1.w = saturate(tmp1.w ? tmp2.x : tmp2.w);
                tmp2.x = saturate(tmp1.y);
                tmp2.x = abs(tmp1.x) + tmp2.x;
                tmp2.x = abs(tmp1.z) + tmp2.x;
                tmp1.w = tmp1.w * tmp2.x;
                tmp8 = _Color01 - _Color31;
                tmp8 = tmp5.xxxx * tmp8 + _Color31;
                tmp9 = _Color11 - tmp8;
                tmp8 = tmp5.yyyy * tmp9 + tmp8;
                tmp9 = _Color21 - tmp8;
                tmp8 = tmp5.zzzz * tmp9 + tmp8;
                tmp2.x = 1.0 - tmp5.w;
                tmp5 = _Color41 - tmp8;
                tmp5 = tmp7.xxxx * tmp5 + tmp8;
                tmp8 = _Color51 - tmp5;
                tmp5 = tmp7.yyyy * tmp8 + tmp5;
                tmp8 = _Color61 - tmp5;
                tmp5 = tmp7.zzzz * tmp8 + tmp5;
                tmp7 = _Color71 - tmp5;
                tmp5 = tmp2.zzzz * tmp7 + tmp5;
                tmp2.zw = tmp5.xx + float2(1.0, 2.0);
                tmp1.w = dot(tmp1.xy, tmp2.xy);
                tmp2.z = dot(_WorldSpaceLightPos0.xyz, _WorldSpaceLightPos0.xyz);
                tmp2.z = rsqrt(tmp2.z);
                tmp6.xzw = tmp2.zzz * _WorldSpaceLightPos0.xyz;
                tmp3.xyz = tmp3.xyz * tmp0.www + tmp6.xzw;
                tmp0.w = dot(tmp1.xyz, tmp6.xyz);
                tmp2.z = dot(tmp3.xyz, tmp3.xyz);
                tmp2.z = rsqrt(tmp2.z);
                tmp3.xyz = tmp2.zzz * tmp3.xyz;
                tmp2.z = dot(tmp3.xyz, tmp1.xyz);
                tmp2.z = max(tmp2.z, 0.0);
                tmp2.z = log(tmp2.z);
                tmp3.xyz = tmp5.xxx * float3(8.0, 0.75, -0.1) + float3(-1.0, 0.25, 0.5);
                tmp3.x = exp(tmp3.x);
                tmp3.x = tmp2.z * tmp3.x;
                tmp2.z = tmp2.z * 64.0;
                tmp2.z = exp(tmp2.z);
                tmp6.xzw = tmp2.zzz * _LightColor0.xyz;
                tmp6.xzw = tmp5.xxx * tmp6.xzw;
                tmp2.z = exp(tmp3.x);
                tmp3.x = tmp5.x + tmp5.x;
                tmp3.x = saturate(tmp3.y * tmp3.x);
                tmp2.z = tmp2.z * tmp3.x;
                tmp3.xy = tmp5.xx * float2(0.75, 3.0);
                tmp2.z = saturate(tmp2.z * tmp3.y);
                tmp3.w = max(tmp0.w, 0.0);
                tmp7.xy = tmp3.ww * float2(1.666667, 20.0) + float2(-0.3333333, -3.0);
                tmp7.y = max(tmp7.y, 0.0);
                tmp7.x = saturate(tmp7.x);
                tmp7.y = min(tmp7.y, 0.8);
                tmp7.x = tmp7.y + tmp7.x;
                tmp3.w = tmp3.w * tmp2.z + tmp7.x;
                tmp1.w = tmp1.w + tmp3.w;
                tmp1.w = tmp1.w * inp.color.x;
                tmp3.w = dot(_LightColor0.xyz, float3(0.3, 0.59, 0.11));
                tmp7.x = tmp1.w * tmp3.w;
                tmp1.w = -tmp1.w * tmp3.w + inp.color.x;
                tmp1.w = tmp4.x * tmp1.w + tmp7.x;
                tmp3.w = inp.color.x * tmp2.z + -tmp1.w;
                tmp3.w = tmp4.x * tmp3.w + tmp1.w;
                tmp1.w = saturate(tmp1.w);
                tmp7.xy = tmp3.ww * float2(5.0, 2.666667);
                tmp7.xy = saturate(tmp7.xy);
                tmp7.zw = saturate(tmp3.ww * float2(-1.111111, -2.181818) + float2(1.111111, 1.2));
                tmp3.w = log(tmp3.w);
                tmp7.xy = tmp7.zw * tmp7.xy;
                tmp3.xy = tmp3.yx * tmp7.yx;
                tmp3.x = saturate(tmp3.x);
                tmp3.y = log(tmp3.y);
                tmp2.w = tmp2.w * tmp3.y;
                tmp2.w = exp(tmp2.w);
                tmp2.w = min(tmp2.w, 1.0);
                tmp3.y = tmp5.x * 2.0 + 1.0;
                tmp3.y = tmp3.w * tmp3.y;
                tmp3.y = exp(tmp3.y);
                tmp3.y = min(tmp3.y, 1.0);
                tmp3.x = tmp3.y - tmp3.x;
                tmp3.x = max(tmp3.x, 0.0);
                tmp3.x = tmp2.w + tmp3.x;
                tmp3.x = min(tmp3.x, 1.0);
                tmp3.yw = tmp3.xx * float2(1.49925, 3.003003);
                tmp3.yw = min(tmp3.yw, float2(1.0, 1.0));
                tmp5.yzw = tmp5.yzw - tmp4.yzw;
                tmp7.xyz = tmp5.xxx * float3(1.6, -0.1, 0.3) + float3(-0.8, 0.6, 1.2);
                tmp4.yzw = tmp1.www * tmp5.yzw + tmp4.yzw;
                tmp1.w = saturate(tmp2.x + tmp4.x);
                tmp5.xy = tmp4.wz;
                tmp8.xy = tmp4.zw - tmp5.xy;
                tmp4.x = tmp5.y >= tmp4.w;
                tmp4.x = tmp4.x ? 1.0 : 0.0;
                tmp5.zw = float2(-1.0, 0.6666667);
                tmp8.zw = float2(1.0, -1.0);
                tmp5 = tmp4.xxxx * tmp8.xywz + tmp5.xywz;
                tmp4.x = tmp4.y >= tmp5.x;
                tmp4.x = tmp4.x ? 1.0 : 0.0;
                tmp8.z = tmp5.w;
                tmp5.w = tmp4.y;
                tmp8.xyw = tmp5.wyx;
                tmp8 = tmp8 - tmp5;
                tmp5 = tmp4.xxxx * tmp8 + tmp5;
                tmp4.x = min(tmp5.y, tmp5.w);
                tmp4.x = tmp5.x - tmp4.x;
                tmp7.w = tmp4.x * 6.0 + 0.0;
                tmp5.y = tmp5.w - tmp5.y;
                tmp5.y = tmp5.y / tmp7.w;
                tmp5.y = tmp5.y + tmp5.z;
                tmp8.xyz = abs(tmp5.yyy) + float3(-0.05, -0.3833334, 0.2833333);
                tmp5.yzw = abs(tmp5.yyy) + float3(0.01, -0.3233334, 0.3433333);
                tmp5.yzw = frac(tmp5.yzw);
                tmp5.yzw = -tmp5.yzw * float3(2.0, 2.0, 2.0) + float3(1.0, 1.0, 1.0);
                tmp5.yzw = saturate(abs(tmp5.yzw) * float3(3.0, 3.0, 3.0) + float3(-1.0, -1.0, -1.0));
                tmp5.yzw = tmp5.yzw - float3(1.0, 1.0, 1.0);
                tmp8.xyz = frac(tmp8.xyz);
                tmp8.xyz = -tmp8.xyz * float3(2.0, 2.0, 2.0) + float3(1.0, 1.0, 1.0);
                tmp8.xyz = saturate(abs(tmp8.xyz) * float3(3.0, 3.0, 3.0) + float3(-1.0, -1.0, -1.0));
                tmp8.xyz = tmp8.xyz - float3(1.0, 1.0, 1.0);
                tmp7.w = tmp5.x + 0.0;
                tmp4.x = tmp4.x / tmp7.w;
                tmp8.xyz = tmp4.xxx * tmp8.xyz + float3(1.0, 1.0, 1.0);
                tmp5.yzw = tmp4.xxx * tmp5.yzw + float3(1.0, 1.0, 1.0);
                tmp9.xyz = tmp5.xxx * tmp8.xyz;
                tmp4.x = dot(tmp9.xyz, float3(0.3, 0.59, 0.11));
                tmp10.xyz = -tmp8.xyz * tmp5.xxx + tmp4.xxx;
                tmp8.xyz = tmp8.xyz * tmp5.xxx + -tmp10.xyz;
                tmp9.xyz = tmp10.xyz * float3(0.2, 0.2, 0.2) + tmp9.xyz;
                tmp10.xyz = -tmp8.xyz * tmp3.zzz + tmp4.yzw;
                tmp8.xyz = tmp3.zzz * tmp8.xyz;
                tmp10.xyz = tmp3.yyy * tmp10.xyz + tmp8.xyz;
                tmp10.xyz = -tmp9.xyz * tmp7.yyy + tmp10.xyz;
                tmp9.xyz = tmp7.yyy * tmp9.xyz;
                tmp3.yzw = tmp3.www * tmp10.xyz + tmp9.xyz;
                tmp9.xyz = tmp5.xxx * tmp5.yzw;
                tmp4.x = dot(tmp9.xyz, float3(0.3, 0.59, 0.11));
                tmp5.xyz = -tmp5.yzw * tmp5.xxx + tmp4.xxx;
                tmp5.xyz = tmp5.xyz * float3(0.05, 0.05, 0.05) + tmp9.xyz;
                tmp5.xyz = saturate(tmp7.zzz * tmp5.xyz);
                tmp7.x = saturate(tmp7.x);
                tmp5.xyz = tmp5.xyz - tmp4.yzw;
                tmp4.x = tmp3.x * 1.49925 + -0.4992504;
                tmp4.x = max(tmp4.x, 0.0);
                tmp4.xyz = tmp4.xxx * tmp5.xyz + tmp4.yzw;
                tmp4.xyz = tmp4.xyz - tmp3.yzw;
                tmp3.xyz = tmp3.xxx * tmp4.xyz + tmp3.yzw;
                tmp3.w = tmp3.y >= tmp3.z;
                tmp3.w = tmp3.w ? 1.0 : 0.0;
                tmp4.xy = tmp3.zy;
                tmp5.xy = tmp3.yz - tmp4.xy;
                tmp4.zw = float2(-1.0, 0.6666667);
                tmp5.zw = float2(1.0, -1.0);
                tmp4 = tmp3.wwww * tmp5.xywz + tmp4.xywz;
                tmp3.w = tmp3.x >= tmp4.x;
                tmp3.w = tmp3.w ? 1.0 : 0.0;
                tmp5.z = tmp4.w;
                tmp4.w = tmp3.x;
                tmp5.xyw = tmp4.wyx;
                tmp5 = tmp5 - tmp4;
                tmp4 = tmp3.wwww * tmp5 + tmp4;
                tmp3.w = min(tmp4.y, tmp4.w);
                tmp3.w = tmp4.x - tmp3.w;
                tmp5.x = tmp3.w * 6.0 + 0.0;
                tmp4.y = tmp4.w - tmp4.y;
                tmp4.y = tmp4.y / tmp5.x;
                tmp4.y = tmp4.y + tmp4.z;
                tmp4.yzw = abs(tmp4.yyy) + float3(-0.125, -0.4583333, 0.2083333);
                tmp4.yzw = frac(tmp4.yzw);
                tmp4.yzw = -tmp4.yzw * float3(2.0, 2.0, 2.0) + float3(1.0, 1.0, 1.0);
                tmp4.yzw = saturate(abs(tmp4.yzw) * float3(3.0, 3.0, 3.0) + float3(-1.0, -1.0, -1.0));
                tmp4.yzw = tmp4.yzw - float3(1.0, 1.0, 1.0);
                tmp5.x = tmp4.x + 0.0;
                tmp3.w = tmp3.w / tmp5.x;
                tmp4.yzw = tmp3.www * tmp4.yzw + float3(1.0, 1.0, 1.0);
                tmp5.xyz = tmp4.xxx * tmp4.yzw;
                tmp3.w = dot(tmp5.xyz, float3(0.3, 0.59, 0.11));
                tmp4.xyz = -tmp4.yzw * tmp4.xxx + tmp3.www;
                tmp4.xyz = tmp4.xyz * float3(0.1, 0.1, 0.1) + tmp5.xyz;
                tmp4.xyz = tmp4.xyz - tmp3.xyz;
                tmp3.xyz = tmp2.www * tmp4.xyz + tmp3.xyz;
                tmp4.xyz = tmp3.xyz * float3(1.333, 1.333, 1.333);
                tmp2.w = dot(tmp4.xyz, float3(0.3, 0.59, 0.11));
                tmp3.xyz = -tmp3.xyz * float3(1.333, 1.333, 1.333) + tmp2.www;
                tmp3.xyz = tmp3.xyz * tmp7.xxx;
                tmp3.xyz = saturate(tmp2.zzz * tmp3.xyz + tmp4.xyz);
                tmp2.z = _Time.y * 6.283;
                tmp2.z = sin(tmp2.z);
                tmp2.zw = tmp2.zz * float2(0.35, 0.05) + float2(0.85, 0.95);
                tmp2.w = tmp2.w - tmp2.z;
                tmp3.w = _SpiralColor * 2.0 + -1.0;
                tmp2.z = abs(tmp3.w) * tmp2.w + tmp2.z;
                tmp4.x = tmp2.z * inp.color.x;
                tmp2.z = _GlowSpeed * _Time.y;
                tmp5.y = frac(tmp2.z);
                tmp5.x = 0.0;
                tmp4.y = _SpiralColor;
                tmp2.zw = tmp4.xy + tmp5.xy;
                tmp4 = tex2D(_GlowRamp, tmp2.zw);
                tmp2.z = tmp2.x * _GlowMultiplier;
                tmp2.z = tmp2.z * 3.0;
                tmp4.xyz = tmp4.xyz * tmp2.zzz + -tmp3.xyz;
                tmp2.xzw = tmp2.xxx * tmp4.xyz + tmp3.xyz;
                tmp3.xyz = tmp2.xzw * float3(0.1, 0.1, 0.1);
                tmp4.xyz = glstate_lightmodel_ambient.xyz + glstate_lightmodel_ambient.xyz;
                tmp5.xyz = -tmp3.xyz * tmp4.xyz + tmp2.xzw;
                tmp3.xyz = tmp3.xyz * tmp4.xyz;
                tmp3.xyz = tmp1.www * tmp5.xyz + tmp3.xyz;
                tmp5.xy = tmp1.yy * unity_MatrixV._m01_m11;
                tmp1.xy = unity_MatrixV._m00_m10 * tmp1.xx + tmp5.xy;
                tmp1.xy = unity_MatrixV._m02_m12 * tmp1.zz + tmp1.xy;
                tmp1.xy = tmp1.xy * float2(0.5, 0.5) + float2(0.5, 0.5);
                tmp5 = tex2D(_Rim, tmp1.xy);
                tmp1.xyz = tmp5.xyz * inp.color.xxx;
                tmp1.xyz = tmp1.xyz * _RimStrength.xxx;
                tmp3.w = dot(tmp4.xyz, float3(0.3, 0.59, 0.11));
                tmp5.xyz = -glstate_lightmodel_ambient.xyz * float3(2.0, 2.0, 2.0) + tmp3.www;
                tmp5.xyz = tmp5.xyz * float3(0.5, 0.5, 0.5) + tmp4.xyz;
                tmp7.xyz = tmp1.xyz * tmp5.xyz;
                tmp1.xyz = tmp1.xyz * tmp5.xyz + float3(-0.5, -0.5, -0.5);
                tmp1.xyz = -tmp1.xyz * float3(2.0, 2.0, 2.0) + float3(1.0, 1.0, 1.0);
                tmp1.xyz = -tmp1.xyz * tmp6.yyy + float3(1.0, 1.0, 1.0);
                tmp5.xyz = tmp2.yyy * tmp7.xyz;
                tmp7.xyz = tmp7.xyz > float3(0.5, 0.5, 0.5);
                tmp5.xyz = tmp5.xyz + tmp5.xyz;
                tmp1.xyz = tmp7.xyz ? tmp1.xyz : tmp5.xyz;
                tmp1.xyz = tmp1.xyz + tmp3.xyz;
                tmp3.xyz = tmp8.xyz * float3(0.5, 0.5, 0.5);
                tmp5.xyz = -tmp8.xyz * float3(0.5, 0.5, 0.5) + float3(1.0, 1.0, 1.0);
                tmp3.xyz = tmp0.www * tmp5.xyz + tmp3.xyz;
                tmp3.xyz = max(tmp3.xyz, float3(0.0, 0.0, 0.0));
                tmp3.xyz = tmp3.xyz * _LightColor0.xyz + tmp4.xyz;
                tmp0.w = inp.color.x * 0.5 + 0.5;
                tmp4.xyw = tmp2.zwx * tmp0.www;
                tmp5.xy = tmp4.yx;
                tmp2.xy = tmp0.ww * tmp2.zw + -tmp5.xy;
                tmp0.w = tmp5.y >= tmp4.y;
                tmp0.w = tmp0.w ? 1.0 : 0.0;
                tmp5.zw = float2(-1.0, 0.6666667);
                tmp2.zw = float2(1.0, -1.0);
                tmp2 = tmp0.wwww * tmp2 + tmp5;
                tmp0.w = tmp4.w >= tmp2.x;
                tmp0.w = tmp0.w ? 1.0 : 0.0;
                tmp4.xyz = tmp2.xyw;
                tmp2.xyw = tmp4.wyx;
                tmp2 = tmp2 - tmp4;
                tmp2 = tmp0.wwww * tmp2 + tmp4;
                tmp0.w = min(tmp2.y, tmp2.w);
                tmp0.w = tmp2.x - tmp0.w;
                tmp3.w = tmp0.w * 6.0 + 0.0;
                tmp2.y = tmp2.w - tmp2.y;
                tmp2.y = tmp2.y / tmp3.w;
                tmp2.y = tmp2.y + tmp2.z;
                tmp0.x = tmp0.x * 0.04 + abs(tmp2.y);
                tmp2.yzw = tmp0.xxx + float3(0.0, -0.3333333, 0.3333333);
                tmp2.yzw = frac(tmp2.yzw);
                tmp2.yzw = -tmp2.yzw * float3(2.0, 2.0, 2.0) + float3(1.0, 1.0, 1.0);
                tmp2.yzw = saturate(abs(tmp2.yzw) * float3(3.0, 3.0, 3.0) + float3(-1.0, -1.0, -1.0));
                tmp2.yzw = tmp2.yzw - float3(1.0, 1.0, 1.0);
                tmp0.x = tmp2.x + 0.0;
                tmp0.z = tmp0.z * 0.075 + tmp2.x;
                tmp0.x = tmp0.w / tmp0.x;
                tmp0.x = tmp0.y * 0.05 + tmp0.x;
                tmp0.xyw = tmp0.xxx * tmp2.yzw + float3(1.0, 1.0, 1.0);
                tmp0.xyz = tmp0.zzz * tmp0.xyw;
                tmp0.xyz = tmp1.www * -tmp0.xyz + tmp0.xyz;
                tmp0.xyz = tmp3.xyz * tmp0.xyz + tmp6.xzw;
                o.sv_target.xyz = tmp1.xyz + tmp0.xyz;
                o.sv_target.w = 1.0;
                return o;
			}
			ENDCG
		}
		Pass {
			Name "FORWARD_DELTA"
			Tags { "LIGHTMODE" = "FORWARDADD" "PreviewType" = "Plane" "RenderType" = "Opaque" "SHADOWSUPPORT" = "true" }
			Blend One One, One One
			GpuProgramID 98947
			CGPROGRAM
			#pragma vertex vert
			#pragma fragment frag
			
			#include "UnityCG.cginc"
			struct v2f
			{
				float4 position : SV_POSITION0;
				float2 texcoord : TEXCOORD0;
				float2 texcoord1 : TEXCOORD1;
				float4 texcoord2 : TEXCOORD2;
				float3 texcoord3 : TEXCOORD3;
				float3 texcoord4 : TEXCOORD4;
				float3 texcoord5 : TEXCOORD5;
				float4 color : COLOR0;
				float3 texcoord6 : TEXCOORD6;
			};
			struct fout
			{
				float4 sv_target : SV_Target0;
			};
			// $Globals ConstantBuffers for Vertex Shader
			float4x4 unity_WorldToLight;
			// $Globals ConstantBuffers for Fragment Shader
			float4 _LightColor0;
			float4 _Color01;
			float4 _Color21;
			float4 _Color11;
			float4 _Color31;
			float4 _Color00;
			float4 _Color10;
			float4 _Color20;
			float4 _Color30;
			float _SpiralColor;
			float4 _Color41;
			float4 _Color51;
			float4 _Color61;
			float4 _Color71;
			float4 _Color40;
			float4 _Color50;
			float4 _Color60;
			float4 _Color70;
			float4 _Normal_ST;
			float _NRMUV1;
			float _NRMTriplanar;
			float4 _PaintStrokes_ST;
			float _PaintMaskTriplanar;
			float _GlowMultiplier;
			float _GlowSpeed;
			// Custom ConstantBuffers for Vertex Shader
			// Custom ConstantBuffers for Fragment Shader
			// Texture params for Vertex Shader
			// Texture params for Fragment Shader
			sampler2D _Normal;
			sampler2D _LightTexture0;
			sampler2D _ColorMask;
			sampler2D _PaintStrokes;
			sampler2D _GlowRamp;
			
			// Keywords: POINT
			v2f vert(appdata_full v)
			{
                v2f o;
                float4 tmp0;
                float4 tmp1;
                float4 tmp2;
                float4 tmp3;
                tmp0 = v.vertex.yyyy * unity_ObjectToWorld._m01_m11_m21_m31;
                tmp0 = unity_ObjectToWorld._m00_m10_m20_m30 * v.vertex.xxxx + tmp0;
                tmp0 = unity_ObjectToWorld._m02_m12_m22_m32 * v.vertex.zzzz + tmp0;
                tmp1 = tmp0 + unity_ObjectToWorld._m03_m13_m23_m33;
                tmp0 = unity_ObjectToWorld._m03_m13_m23_m33 * v.vertex.wwww + tmp0;
                tmp2 = tmp1.yyyy * unity_MatrixVP._m01_m11_m21_m31;
                tmp2 = unity_MatrixVP._m00_m10_m20_m30 * tmp1.xxxx + tmp2;
                tmp2 = unity_MatrixVP._m02_m12_m22_m32 * tmp1.zzzz + tmp2;
                o.position = unity_MatrixVP._m03_m13_m23_m33 * tmp1.wwww + tmp2;
                o.texcoord.xy = v.texcoord.xy;
                o.texcoord1.xy = v.texcoord1.xy;
                o.texcoord2 = tmp0;
                tmp1.x = dot(v.normal.xyz, unity_WorldToObject._m00_m10_m20);
                tmp1.y = dot(v.normal.xyz, unity_WorldToObject._m01_m11_m21);
                tmp1.z = dot(v.normal.xyz, unity_WorldToObject._m02_m12_m22);
                tmp1.w = dot(tmp1.xyz, tmp1.xyz);
                tmp1.w = rsqrt(tmp1.w);
                tmp1.xyz = tmp1.www * tmp1.xyz;
                o.texcoord3.xyz = tmp1.xyz;
                tmp2.xyz = v.tangent.yyy * unity_ObjectToWorld._m01_m11_m21;
                tmp2.xyz = unity_ObjectToWorld._m00_m10_m20 * v.tangent.xxx + tmp2.xyz;
                tmp2.xyz = unity_ObjectToWorld._m02_m12_m22 * v.tangent.zzz + tmp2.xyz;
                tmp1.w = dot(tmp2.xyz, tmp2.xyz);
                tmp1.w = rsqrt(tmp1.w);
                tmp2.xyz = tmp1.www * tmp2.xyz;
                o.texcoord4.xyz = tmp2.xyz;
                tmp3.xyz = tmp1.zxy * tmp2.yzx;
                tmp1.xyz = tmp1.yzx * tmp2.zxy + -tmp3.xyz;
                tmp1.xyz = tmp1.xyz * v.tangent.www;
                tmp1.w = dot(tmp1.xyz, tmp1.xyz);
                tmp1.w = rsqrt(tmp1.w);
                o.texcoord5.xyz = tmp1.www * tmp1.xyz;
                o.color = v.color;
                tmp1.xyz = tmp0.yyy * unity_WorldToLight._m01_m11_m21;
                tmp1.xyz = unity_WorldToLight._m00_m10_m20 * tmp0.xxx + tmp1.xyz;
                tmp0.xyz = unity_WorldToLight._m02_m12_m22 * tmp0.zzz + tmp1.xyz;
                o.texcoord6.xyz = unity_WorldToLight._m03_m13_m23 * tmp0.www + tmp0.xyz;
                return o;
			}
			// Keywords: POINT
			fout frag(v2f inp)
			{
                fout o;
                float4 tmp0;
                float4 tmp1;
                float4 tmp2;
                float4 tmp3;
                float4 tmp4;
                float4 tmp5;
                float4 tmp6;
                float4 tmp7;
                float4 tmp8;
                float4 tmp9;
                tmp0.xy = inp.texcoord2.zx * _PaintStrokes_ST.xy + _PaintStrokes_ST.zw;
                tmp0 = tex2D(_PaintStrokes, tmp0.xy);
                tmp1 = inp.texcoord2.xyyz * _PaintStrokes_ST + _PaintStrokes_ST;
                tmp2 = tex2D(_PaintStrokes, tmp1.zw);
                tmp1 = tex2D(_PaintStrokes, tmp1.xy);
                tmp0.y = tmp2.x - tmp1.x;
                tmp0.z = dot(inp.texcoord3.xyz, inp.texcoord3.xyz);
                tmp0.z = rsqrt(tmp0.z);
                tmp1.yzw = tmp0.zzz * inp.texcoord3.xyz;
                tmp0.y = abs(tmp1.y) * tmp0.y + tmp1.x;
                tmp0.x = tmp0.x - tmp0.y;
                tmp0.x = abs(tmp1.z) * tmp0.x + tmp0.y;
                tmp0.y = tmp1.x - tmp0.x;
                tmp0.x = abs(tmp1.w) * tmp0.y + tmp0.x;
                tmp2.xy = inp.texcoord2.zx * _PaintStrokes_ST.xy;
                tmp3 = tmp2.xyxy * float4(0.9, 0.9, 1.1, 1.1) + _PaintStrokes_ST;
                tmp2.xy = tmp2.xy * float2(0.65, 0.65) + _PaintStrokes_ST.zw;
                tmp2 = tex2D(_PaintStrokes, tmp2.xy);
                tmp4 = tex2D(_PaintStrokes, tmp3.xy);
                tmp3 = tex2D(_PaintStrokes, tmp3.zw);
                tmp5 = inp.texcoord2.xyyz * _PaintStrokes_ST;
                tmp6 = tmp5 * float4(0.9, 0.9, 0.9, 0.9) + _PaintStrokes_ST;
                tmp7 = tex2D(_PaintStrokes, tmp6.zw);
                tmp6 = tex2D(_PaintStrokes, tmp6.xy);
                tmp0.w = tmp7.y - tmp6.y;
                tmp0.w = abs(tmp1.y) * tmp0.w + tmp6.y;
                tmp1.x = tmp4.y - tmp0.w;
                tmp0.w = abs(tmp1.z) * tmp1.x + tmp0.w;
                tmp1.x = tmp6.y - tmp0.w;
                tmp0.y = abs(tmp1.w) * tmp1.x + tmp0.w;
                tmp4 = tmp5 * float4(1.1, 1.1, 1.1, 1.1) + _PaintStrokes_ST;
                tmp5 = tmp5 * float4(0.55, 0.55, 0.45, 0.45) + _PaintStrokes_ST;
                tmp6 = tex2D(_PaintStrokes, tmp4.zw);
                tmp4 = tex2D(_PaintStrokes, tmp4.xy);
                tmp0.w = tmp6.y - tmp4.y;
                tmp0.w = abs(tmp1.y) * tmp0.w + tmp4.y;
                tmp1.x = tmp3.y - tmp0.w;
                tmp0.w = abs(tmp1.z) * tmp1.x + tmp0.w;
                tmp1.x = tmp4.y - tmp0.w;
                tmp0.z = abs(tmp1.w) * tmp1.x + tmp0.w;
                tmp3.xyz = float3(1.0, 1.0, 1.0) - tmp0.xyz;
                tmp4 = tex2D(_PaintStrokes, tmp5.zw);
                tmp5 = tex2D(_PaintStrokes, tmp5.xy);
                tmp4.xyz = tmp4.xyz - tmp5.xyz;
                tmp4.xyz = abs(tmp1.yyy) * tmp4.xyz + tmp5.xyz;
                tmp2.xyz = tmp2.xyz - tmp4.xyz;
                tmp2.xyz = abs(tmp1.zzz) * tmp2.xyz + tmp4.xyz;
                tmp4.xyz = tmp5.xyz - tmp2.xyz;
                tmp2.xyz = abs(tmp1.www) * tmp4.xyz + tmp2.xyz;
                tmp4.xyz = tmp2.xyz - float3(0.5, 0.5, 0.5);
                tmp4.xyz = -tmp4.xyz * float3(2.0, 2.0, 2.0) + float3(1.0, 1.0, 1.0);
                tmp3.xyz = -tmp4.xyz * tmp3.xyz + float3(1.0, 1.0, 1.0);
                tmp0.xyz = tmp0.xyz * tmp2.xyz;
                tmp2.xyz = tmp2.xyz > float3(0.5, 0.5, 0.5);
                tmp0.xyz = tmp0.xyz + tmp0.xyz;
                tmp0.xyz = saturate(tmp2.xyz ? tmp3.xyz : tmp0.xyz);
                tmp2.xy = inp.texcoord1.xy - inp.texcoord.xy;
                tmp2.xy = _NRMUV1.xx * tmp2.xy + inp.texcoord.xy;
                tmp2.zw = tmp2.xy * _PaintStrokes_ST.xy + _PaintStrokes_ST.zw;
                tmp2.xy = tmp2.xy * _Normal_ST.xy + _Normal_ST.zw;
                tmp3 = tex2D(_Normal, tmp2.xy);
                tmp2 = tex2D(_PaintStrokes, tmp2.zw);
                tmp0.xyz = tmp0.xyz - tmp2.xyz;
                tmp0.xyz = _PaintMaskTriplanar.xxx * tmp0.xyz + tmp2.xyz;
                tmp0.w = tmp0.x * 0.3 + 0.35;
                tmp0.xyz = tmp0.xyz - float3(0.5, 0.5, 0.5);
                tmp1.x = 1.0 - tmp0.w;
                tmp2.xy = inp.texcoord2.zx * _Normal_ST.xy + _Normal_ST.zw;
                tmp2 = tex2D(_Normal, tmp2.xy);
                tmp2.x = tmp2.w * tmp2.x;
                tmp2.xy = tmp2.xy * float2(2.0, 2.0) + float2(-1.0, -1.0);
                tmp2.w = dot(tmp2.xy, tmp2.xy);
                tmp2.w = min(tmp2.w, 1.0);
                tmp2.w = 1.0 - tmp2.w;
                tmp2.z = sqrt(tmp2.w);
                tmp4 = inp.texcoord2.xyyz * _Normal_ST + _Normal_ST;
                tmp5 = tex2D(_Normal, tmp4.zw);
                tmp4 = tex2D(_Normal, tmp4.xy);
                tmp5.x = tmp5.w * tmp5.x;
                tmp5.xy = tmp5.xy * float2(2.0, 2.0) + float2(-1.0, -1.0);
                tmp2.w = dot(tmp5.xy, tmp5.xy);
                tmp2.w = min(tmp2.w, 1.0);
                tmp2.w = 1.0 - tmp2.w;
                tmp5.z = sqrt(tmp2.w);
                tmp4.x = tmp4.w * tmp4.x;
                tmp4.xy = tmp4.xy * float2(2.0, 2.0) + float2(-1.0, -1.0);
                tmp2.w = dot(tmp4.xy, tmp4.xy);
                tmp2.w = min(tmp2.w, 1.0);
                tmp2.w = 1.0 - tmp2.w;
                tmp4.z = sqrt(tmp2.w);
                tmp5.xyz = tmp5.xyz - tmp4.xyz;
                tmp5.xyz = abs(tmp1.yyy) * tmp5.xyz + tmp4.xyz;
                tmp2.xyz = tmp2.xyz - tmp5.xyz;
                tmp2.xyz = abs(tmp1.zzz) * tmp2.xyz + tmp5.xyz;
                tmp4.xyz = tmp4.xyz - tmp2.xyz;
                tmp2.xyz = abs(tmp1.www) * tmp4.xyz + tmp2.xyz;
                tmp3.x = tmp3.w * tmp3.x;
                tmp3.xy = tmp3.xy * float2(2.0, 2.0) + float2(-1.0, -1.0);
                tmp2.w = dot(tmp3.xy, tmp3.xy);
                tmp2.w = min(tmp2.w, 1.0);
                tmp2.w = 1.0 - tmp2.w;
                tmp3.z = sqrt(tmp2.w);
                tmp2.xyz = tmp2.xyz - tmp3.xyz;
                tmp2.xyz = _NRMTriplanar.xxx * tmp2.xyz + tmp3.xyz;
                tmp3.xyz = tmp2.yyy * inp.texcoord5.xyz;
                tmp2.xyw = tmp2.xxx * inp.texcoord4.xyz + tmp3.xyz;
                tmp1.yzw = tmp2.zzz * tmp1.yzw + tmp2.xyw;
                tmp2.x = dot(tmp1.xyz, tmp1.xyz);
                tmp2.x = rsqrt(tmp2.x);
                tmp1.yzw = tmp1.yzw * tmp2.xxx;
                tmp2.xyz = _WorldSpaceCameraPos - inp.texcoord2.xyz;
                tmp2.w = dot(tmp2.xyz, tmp2.xyz);
                tmp2.w = rsqrt(tmp2.w);
                tmp3.xyz = tmp2.www * tmp2.xyz;
                tmp3.x = dot(tmp1.xyz, tmp3.xyz);
                tmp3.x = max(tmp3.x, 0.0);
                tmp3.x = 1.0 - tmp3.x;
                tmp3.x = log(tmp3.x);
                tmp4 = _Color00 - _Color30;
                tmp5 = tex2D(_ColorMask, inp.texcoord.xy);
                tmp4 = tmp5.xxxx * tmp4 + _Color30;
                tmp6 = _Color10 - tmp4;
                tmp4 = tmp5.yyyy * tmp6 + tmp4;
                tmp6 = _Color20 - tmp4;
                tmp4 = tmp5.zzzz * tmp6 + tmp4;
                tmp6 = _Color40 - tmp4;
                tmp3.yzw = saturate(tmp5.xyz * float3(1.49925, 1.49925, 1.49925) + float3(-0.4992504, -0.4992504, -0.4992504));
                tmp7.x = tmp3.z * tmp3.y;
                tmp7.x = tmp3.w * tmp7.x;
                tmp3.yzw = tmp3.yyz * tmp3.wzw + -tmp7.xxx;
                tmp4 = tmp3.yyyy * tmp6 + tmp4;
                tmp6 = _Color50 - tmp4;
                tmp4 = tmp3.zzzz * tmp6 + tmp4;
                tmp6 = _Color60 - tmp4;
                tmp4 = tmp3.wwww * tmp6 + tmp4;
                tmp6 = _Color70 - tmp4;
                tmp4 = tmp7.xxxx * tmp6 + tmp4;
                tmp6.x = tmp4.x * 2.5 + 1.5;
                tmp3.x = tmp3.x * tmp6.x;
                tmp3.x = exp(tmp3.x);
                tmp3.x = tmp3.x * tmp3.x;
                tmp3.x = min(tmp3.x, 1.0);
                tmp6.x = tmp3.x - 0.5;
                tmp6.x = -tmp6.x * 2.0 + 1.0;
                tmp1.x = -tmp6.x * tmp1.x + 1.0;
                tmp0.w = dot(tmp0.xy, tmp3.xy);
                tmp3.x = tmp3.x > 0.5;
                tmp0.w = saturate(tmp3.x ? tmp1.x : tmp0.w);
                tmp1.x = saturate(tmp1.z);
                tmp1.x = abs(tmp1.y) + tmp1.x;
                tmp1.x = abs(tmp1.w) + tmp1.x;
                tmp0.w = tmp0.w * tmp1.x;
                tmp6.xyz = _WorldSpaceLightPos0.www * -inp.texcoord2.xyz + _WorldSpaceLightPos0.xyz;
                tmp1.x = dot(tmp6.xyz, tmp6.xyz);
                tmp1.x = rsqrt(tmp1.x);
                tmp6.xyz = tmp1.xxx * tmp6.xyz;
                tmp2.xyz = tmp2.xyz * tmp2.www + tmp6.xyz;
                tmp1.x = dot(tmp1.xyz, tmp6.xyz);
                tmp2.w = dot(tmp2.xyz, tmp2.xyz);
                tmp2.w = rsqrt(tmp2.w);
                tmp2.xyz = tmp2.www * tmp2.xyz;
                tmp1.y = dot(tmp2.xyz, tmp1.xyz);
                tmp1.y = max(tmp1.y, 0.0);
                tmp1.y = log(tmp1.y);
                tmp2 = _Color01 - _Color31;
                tmp2 = tmp5.xxxx * tmp2 + _Color31;
                tmp6 = _Color11 - tmp2;
                tmp2 = tmp5.yyyy * tmp6 + tmp2;
                tmp6 = _Color21 - tmp2;
                tmp2 = tmp5.zzzz * tmp6 + tmp2;
                tmp1.z = 1.0 - tmp5.w;
                tmp5 = _Color41 - tmp2;
                tmp2 = tmp3.yyyy * tmp5 + tmp2;
                tmp5 = _Color51 - tmp2;
                tmp2 = tmp3.zzzz * tmp5 + tmp2;
                tmp5 = _Color61 - tmp2;
                tmp2 = tmp3.wwww * tmp5 + tmp2;
                tmp3 = _Color71 - tmp2;
                tmp2 = tmp7.xxxx * tmp3 + tmp2;
                tmp3.xyz = tmp2.xxx * float3(8.0, 0.75, -0.1) + float3(-1.0, 0.25, 0.5);
                tmp1.w = exp(tmp3.x);
                tmp1.w = tmp1.y * tmp1.w;
                tmp1.y = tmp1.y * 64.0;
                tmp1.y = exp(tmp1.y);
                tmp1.w = exp(tmp1.w);
                tmp3.x = tmp2.x + tmp2.x;
                tmp3.x = saturate(tmp3.y * tmp3.x);
                tmp1.w = tmp1.w * tmp3.x;
                tmp3.xy = tmp2.xx * float2(0.75, 3.0);
                tmp1.w = saturate(tmp1.w * tmp3.y);
                tmp3.w = max(tmp1.x, 0.0);
                tmp5.xy = tmp3.ww * float2(1.666667, 20.0) + float2(-0.3333333, -3.0);
                tmp5.y = max(tmp5.y, 0.0);
                tmp5.x = saturate(tmp5.x);
                tmp5.y = min(tmp5.y, 0.8);
                tmp5.x = tmp5.y + tmp5.x;
                tmp3.w = tmp3.w * tmp1.w + tmp5.x;
                tmp5.xy = tmp2.xx + float2(1.0, 2.0);
                tmp3.w = tmp0.w * tmp5.x + tmp3.w;
                tmp0.w = tmp0.w * tmp5.x;
                tmp5.x = dot(inp.texcoord6.xyz, inp.texcoord6.xyz);
                tmp6 = tex2D(_LightTexture0, tmp5.xx);
                tmp0.w = tmp3.w * tmp6.x + tmp0.w;
                tmp5.xzw = tmp6.xxx * _LightColor0.xyz;
                tmp0.w = tmp0.w * inp.color.x;
                tmp3.w = dot(_LightColor0.xyz, float3(0.3, 0.59, 0.11));
                tmp6.x = tmp0.w * tmp3.w;
                tmp0.w = -tmp0.w * tmp3.w + inp.color.x;
                tmp0.w = tmp4.x * tmp0.w + tmp6.x;
                tmp3.w = inp.color.x * tmp1.w + -tmp0.w;
                tmp3.w = tmp4.x * tmp3.w + tmp0.w;
                tmp0.w = saturate(tmp0.w);
                tmp6.xy = tmp3.ww * float2(5.0, 2.666667);
                tmp6.xy = saturate(tmp6.xy);
                tmp6.zw = saturate(tmp3.ww * float2(-1.111111, -2.181818) + float2(1.111111, 1.2));
                tmp3.w = log(tmp3.w);
                tmp6.xy = tmp6.zw * tmp6.xy;
                tmp3.xy = tmp3.yx * tmp6.yx;
                tmp3.x = saturate(tmp3.x);
                tmp3.y = log(tmp3.y);
                tmp3.y = tmp3.y * tmp5.y;
                tmp3.y = exp(tmp3.y);
                tmp5.y = tmp2.x * 2.0 + 1.0;
                tmp3.w = tmp3.w * tmp5.y;
                tmp3.w = exp(tmp3.w);
                tmp3.yw = min(tmp3.yw, float2(1.0, 1.0));
                tmp3.x = tmp3.w - tmp3.x;
                tmp3.x = max(tmp3.x, 0.0);
                tmp3.x = tmp3.y + tmp3.x;
                tmp3.x = min(tmp3.x, 1.0);
                tmp6.xy = tmp3.xx * float2(1.49925, 3.003003);
                tmp6.xy = min(tmp6.xy, float2(1.0, 1.0));
                tmp2.yzw = tmp2.yzw - tmp4.yzw;
                tmp2.yzw = tmp0.www * tmp2.yzw + tmp4.yzw;
                tmp0.w = saturate(tmp1.z + tmp4.x);
                tmp4.xy = tmp2.wz;
                tmp7.xy = tmp2.zw - tmp4.xy;
                tmp3.w = tmp4.y >= tmp2.w;
                tmp3.w = tmp3.w ? 1.0 : 0.0;
                tmp4.zw = float2(-1.0, 0.6666667);
                tmp7.zw = float2(1.0, -1.0);
                tmp4 = tmp3.wwww * tmp7.xywz + tmp4.xywz;
                tmp3.w = tmp2.y >= tmp4.x;
                tmp3.w = tmp3.w ? 1.0 : 0.0;
                tmp7.z = tmp4.w;
                tmp4.w = tmp2.y;
                tmp7.xyw = tmp4.wyx;
                tmp7 = tmp7 - tmp4;
                tmp4 = tmp3.wwww * tmp7 + tmp4;
                tmp3.w = min(tmp4.y, tmp4.w);
                tmp3.w = tmp4.x - tmp3.w;
                tmp5.y = tmp3.w * 6.0 + 0.0;
                tmp4.y = tmp4.w - tmp4.y;
                tmp4.y = tmp4.y / tmp5.y;
                tmp4.y = tmp4.y + tmp4.z;
                tmp7.xyz = abs(tmp4.yyy) + float3(-0.05, -0.3833334, 0.2833333);
                tmp4.yzw = abs(tmp4.yyy) + float3(0.01, -0.3233334, 0.3433333);
                tmp4.yzw = frac(tmp4.yzw);
                tmp4.yzw = -tmp4.yzw * float3(2.0, 2.0, 2.0) + float3(1.0, 1.0, 1.0);
                tmp4.yzw = saturate(abs(tmp4.yzw) * float3(3.0, 3.0, 3.0) + float3(-1.0, -1.0, -1.0));
                tmp4.yzw = tmp4.yzw - float3(1.0, 1.0, 1.0);
                tmp7.xyz = frac(tmp7.xyz);
                tmp7.xyz = -tmp7.xyz * float3(2.0, 2.0, 2.0) + float3(1.0, 1.0, 1.0);
                tmp7.xyz = saturate(abs(tmp7.xyz) * float3(3.0, 3.0, 3.0) + float3(-1.0, -1.0, -1.0));
                tmp7.xyz = tmp7.xyz - float3(1.0, 1.0, 1.0);
                tmp5.y = tmp4.x + 0.0;
                tmp3.w = tmp3.w / tmp5.y;
                tmp7.xyz = tmp3.www * tmp7.xyz + float3(1.0, 1.0, 1.0);
                tmp4.yzw = tmp3.www * tmp4.yzw + float3(1.0, 1.0, 1.0);
                tmp8.xyz = tmp4.xxx * tmp7.xyz;
                tmp3.w = dot(tmp8.xyz, float3(0.3, 0.59, 0.11));
                tmp9.xyz = -tmp7.xyz * tmp4.xxx + tmp3.www;
                tmp7.xyz = tmp7.xyz * tmp4.xxx + -tmp9.xyz;
                tmp8.xyz = tmp9.xyz * float3(0.2, 0.2, 0.2) + tmp8.xyz;
                tmp9.xyz = -tmp7.xyz * tmp3.zzz + tmp2.yzw;
                tmp7.xyz = tmp3.zzz * tmp7.xyz;
                tmp6.xzw = tmp6.xxx * tmp9.xyz + tmp7.xyz;
                tmp9.xyz = tmp2.xxx * float3(1.6, -0.1, 0.3) + float3(-0.8, 0.6, 1.2);
                tmp6.xzw = -tmp8.xyz * tmp9.yyy + tmp6.xzw;
                tmp8.xyz = tmp8.xyz * tmp9.yyy;
                tmp6.xyz = tmp6.yyy * tmp6.xzw + tmp8.xyz;
                tmp8.xyz = tmp4.xxx * tmp4.yzw;
                tmp3.z = dot(tmp8.xyz, float3(0.3, 0.59, 0.11));
                tmp4.xyz = -tmp4.yzw * tmp4.xxx + tmp3.zzz;
                tmp4.xyz = tmp4.xyz * float3(0.05, 0.05, 0.05) + tmp8.xyz;
                tmp4.xyz = saturate(tmp9.zzz * tmp4.xyz);
                tmp9.x = saturate(tmp9.x);
                tmp4.xyz = tmp4.xyz - tmp2.yzw;
                tmp3.z = tmp3.x * 1.49925 + -0.4992504;
                tmp3.z = max(tmp3.z, 0.0);
                tmp2.yzw = tmp3.zzz * tmp4.xyz + tmp2.yzw;
                tmp2.yzw = tmp2.yzw - tmp6.xyz;
                tmp2.yzw = tmp3.xxx * tmp2.yzw + tmp6.xyz;
                tmp3.x = tmp2.z >= tmp2.w;
                tmp3.x = tmp3.x ? 1.0 : 0.0;
                tmp4.xy = tmp2.wz;
                tmp6.xy = tmp2.zw - tmp4.xy;
                tmp4.zw = float2(-1.0, 0.6666667);
                tmp6.zw = float2(1.0, -1.0);
                tmp4 = tmp3.xxxx * tmp6.xywz + tmp4.xywz;
                tmp3.x = tmp2.y >= tmp4.x;
                tmp3.x = tmp3.x ? 1.0 : 0.0;
                tmp6.z = tmp4.w;
                tmp4.w = tmp2.y;
                tmp6.xyw = tmp4.wyx;
                tmp6 = tmp6 - tmp4;
                tmp4 = tmp3.xxxx * tmp6 + tmp4;
                tmp3.x = min(tmp4.y, tmp4.w);
                tmp3.x = tmp4.x - tmp3.x;
                tmp3.z = tmp3.x * 6.0 + 0.0;
                tmp3.w = tmp4.w - tmp4.y;
                tmp3.z = tmp3.w / tmp3.z;
                tmp3.z = tmp3.z + tmp4.z;
                tmp4.yzw = abs(tmp3.zzz) + float3(-0.125, -0.4583333, 0.2083333);
                tmp4.yzw = frac(tmp4.yzw);
                tmp4.yzw = -tmp4.yzw * float3(2.0, 2.0, 2.0) + float3(1.0, 1.0, 1.0);
                tmp4.yzw = saturate(abs(tmp4.yzw) * float3(3.0, 3.0, 3.0) + float3(-1.0, -1.0, -1.0));
                tmp4.yzw = tmp4.yzw - float3(1.0, 1.0, 1.0);
                tmp3.z = tmp4.x + 0.0;
                tmp3.x = tmp3.x / tmp3.z;
                tmp3.xzw = tmp3.xxx * tmp4.yzw + float3(1.0, 1.0, 1.0);
                tmp4.yzw = tmp4.xxx * tmp3.xzw;
                tmp5.y = dot(tmp4.xyz, float3(0.3, 0.59, 0.11));
                tmp3.xzw = -tmp3.xzw * tmp4.xxx + tmp5.yyy;
                tmp3.xzw = tmp3.xzw * float3(0.1, 0.1, 0.1) + tmp4.yzw;
                tmp3.xzw = tmp3.xzw - tmp2.yzw;
                tmp2.yzw = tmp3.yyy * tmp3.xzw + tmp2.yzw;
                tmp3.xyz = tmp2.yzw * float3(1.333, 1.333, 1.333);
                tmp3.w = dot(tmp3.xyz, float3(0.3, 0.59, 0.11));
                tmp2.yzw = -tmp2.yzw * float3(1.333, 1.333, 1.333) + tmp3.www;
                tmp2.yzw = tmp2.yzw * tmp9.xxx;
                tmp2.yzw = saturate(tmp1.www * tmp2.yzw + tmp3.xyz);
                tmp1.w = _Time.y * 6.283;
                tmp1.w = sin(tmp1.w);
                tmp3.xy = tmp1.ww * float2(0.35, 0.05) + float2(0.85, 0.95);
                tmp1.w = tmp3.y - tmp3.x;
                tmp3.y = _SpiralColor * 2.0 + -1.0;
                tmp1.w = abs(tmp3.y) * tmp1.w + tmp3.x;
                tmp3.x = tmp1.w * inp.color.x;
                tmp1.w = _GlowSpeed * _Time.y;
                tmp4.y = frac(tmp1.w);
                tmp4.xzw = float3(0.0, -1.0, 0.6666667);
                tmp3.y = _SpiralColor;
                tmp3.xy = tmp3.xy + tmp4.xy;
                tmp3 = tex2D(_GlowRamp, tmp3.xy);
                tmp1.w = tmp1.z * _GlowMultiplier;
                tmp1.w = tmp1.w * 3.0;
                tmp3.xyz = tmp3.xyz * tmp1.www + -tmp2.yzw;
                tmp2.yzw = tmp1.zzz * tmp3.xyz + tmp2.yzw;
                tmp1.z = inp.color.x * 0.5 + 0.5;
                tmp3.xyw = tmp2.zwy * tmp1.zzz;
                tmp4.xy = tmp3.yx;
                tmp6.xy = tmp1.zz * tmp2.zw + -tmp4.xy;
                tmp1.z = tmp4.y >= tmp3.y;
                tmp1.z = tmp1.z ? 1.0 : 0.0;
                tmp6.zw = float2(1.0, -1.0);
                tmp4 = tmp1.zzzz * tmp6 + tmp4;
                tmp1.z = tmp3.w >= tmp4.x;
                tmp1.z = tmp1.z ? 1.0 : 0.0;
                tmp3.xyz = tmp4.xyw;
                tmp4.xyw = tmp3.wyx;
                tmp4 = tmp4 - tmp3;
                tmp3 = tmp1.zzzz * tmp4 + tmp3;
                tmp1.z = min(tmp3.y, tmp3.w);
                tmp1.z = tmp3.x - tmp1.z;
                tmp1.w = tmp1.z * 6.0 + 0.0;
                tmp2.y = tmp3.w - tmp3.y;
                tmp1.w = tmp2.y / tmp1.w;
                tmp1.w = tmp1.w + tmp3.z;
                tmp0.x = tmp0.x * 0.04 + abs(tmp1.w);
                tmp2.yzw = tmp0.xxx + float3(0.0, -0.3333333, 0.3333333);
                tmp2.yzw = frac(tmp2.yzw);
                tmp2.yzw = -tmp2.yzw * float3(2.0, 2.0, 2.0) + float3(1.0, 1.0, 1.0);
                tmp2.yzw = saturate(abs(tmp2.yzw) * float3(3.0, 3.0, 3.0) + float3(-1.0, -1.0, -1.0));
                tmp2.yzw = tmp2.yzw - float3(1.0, 1.0, 1.0);
                tmp0.x = tmp3.x + 0.0;
                tmp0.z = tmp0.z * 0.075 + tmp3.x;
                tmp0.x = tmp1.z / tmp0.x;
                tmp0.x = tmp0.y * 0.05 + tmp0.x;
                tmp2.yzw = tmp0.xxx * tmp2.yzw + float3(1.0, 1.0, 1.0);
                tmp0.xyz = tmp0.zzz * tmp2.yzw;
                tmp0.xyz = tmp0.www * -tmp0.xyz + tmp0.xyz;
                tmp2.yzw = tmp7.xyz * float3(0.5, 0.5, 0.5);
                tmp3.xyz = -tmp7.xyz * float3(0.5, 0.5, 0.5) + float3(1.0, 1.0, 1.0);
                tmp1.xzw = tmp1.xxx * tmp3.xyz + tmp2.yzw;
                tmp1.xzw = max(tmp1.xzw, float3(0.0, 0.0, 0.0));
                tmp1.xzw = tmp5.xzw * tmp1.xzw;
                tmp2.yzw = tmp1.yyy * tmp5.xzw;
                tmp2.xyz = tmp2.xxx * tmp2.yzw;
                o.sv_target.xyz = tmp1.xzw * tmp0.xyz + tmp2.xyz;
                o.sv_target.w = 0.0;
                return o;
			}
			ENDCG
		}
	}
	Fallback "Diffuse"
	CustomEditor "ShaderForgeMaterialInspector"
}