Shader "SR/Actor/Recolor x8" {
	Properties {
		[NoScaleOffset] _AmbientOcclusion ("Ambient Occlusion", 2D) = "gray" {}
		[MaterialToggle] _AOUV1 ("AO UV 1", Float) = 0
		[Space] [Space] [Space] [NoScaleOffset] _ColorMask ("Color Mask", 2D) = "black" {}
		[NoScaleOffset] _Override ("Override", 2D) = "black" {}
		[MaterialToggle] _OverrideUV1 ("Override UV 1", Float) = 0
		[Space] [Header(Alpha controls Glow and Gloss)] [Header(Red)] _Color00 ("Dark/Glow", Color) = (0.5019608,0,0,0)
		_Color01 ("Light/Gloss", Color) = (1,0,0,0)
		[Header(Green)] _Color10 ("Dark/Glow", Color) = (0,0.5,0,0)
		_Color11 ("Light/Gloss", Color) = (0,1,0,0)
		[Header(Blue)] _Color20 ("Dark/Glow", Color) = (0,0,0.5,0)
		_Color21 ("Light/Gloss", Color) = (0,0,1,0)
		[Header(Black)] _Color30 ("Dark/Glow", Color) = (0,0,0,0)
		_Color31 ("Light/Gloss", Color) = (0.3,0.3,0.3,0)
		[Header(Magenta)] _Color40 ("Dark/Glow", Color) = (0.5,0,0.5,0)
		_Color41 ("Light/Gloss", Color) = (1,0,1,0)
		[Header(Yellow)] _Color50 ("Dark/Glow", Color) = (0.5,0.5,0,0)
		_Color51 ("Light/Gloss", Color) = (1,1,0,0)
		[Header(Cyan)] _Color60 ("Dark/Glow", Color) = (0,0.5,0.5,0)
		_Color61 ("Light/Gloss", Color) = (0,1,1,0)
		[Header(White)] _Color70 ("Dark/Glow", Color) = (0.5,0.5,0.5,0)
		_Color71 ("Light/Gloss", Color) = (1,1,1,0)
		[Space] [Space] [Header(Mask defined by Color Mask Alpha)] [NoScaleOffset] _GlowRamp ("Ramp Alpha (Glow)", 2D) = "black" {}
		_SpiralColor ("Spiral Color", Range(0, 1)) = 0
		_GlowMultiplier ("Glow Multiplier", Float) = 1
		_GlowSpeed ("Glow Speed", Float) = 0
		[Space] [Header(Normals)] _Normal ("Normal", 2D) = "bump" {}
		[MaterialToggle] _NRMUV1 ("NRM UV 1", Float) = 0
		[MaterialToggle] _NRMTriplanar ("NRM Triplanar", Float) = 0
		[Space] _Transparency ("Transparency", Range(0, 1)) = 1
		[NoScaleOffset] _Rim ("Rim", 2D) = "black" {}
		_RimStrength ("Rim Strength", Range(0, 1)) = 1
		_PaintStrokes ("PaintStrokes", 2D) = "gray" {}
		[MaterialToggle] _PaintMaskTriplanar ("PaintMask Triplanar", Float) = 0
		[Space] [Space] [Header(Settings for AlphaClip Fade)] _Assemble ("Assemble", Range(0, 1)) = 1
		_AssembleOffset ("Assemble Offset", Float) = 0.67
		_AssembleDif ("Assemble Dif", Float) = 0.25
		_AssembleDistance ("Assemble Distance", Float) = 15
		_AssembleFalloff ("Assemble Falloff", Float) = 1
		[HideInInspector] _Cutoff ("Alpha cutoff", Range(0, 1)) = 0.5
	}
	SubShader {
		Tags { "DisableBatching" = "true" "PreviewType" = "Plane" "RenderType" = "Opaque" }
		Pass {
			Name "FORWARD"
			Tags { "DisableBatching" = "true" "LIGHTMODE" = "FORWARDBASE" "PreviewType" = "Plane" "RenderType" = "Opaque" "SHADOWSUPPORT" = "true" }
			GpuProgramID 2942
			CGPROGRAM
			#pragma vertex vert
			#pragma fragment frag
			
			#include "UnityCG.cginc"
			struct v2f
			{
				float4 position : SV_POSITION0;
				float2 texcoord : TEXCOORD0;
				float2 texcoord1 : TEXCOORD1;
				float4 texcoord2 : TEXCOORD2;
				float3 texcoord3 : TEXCOORD3;
				float3 texcoord4 : TEXCOORD4;
				float3 texcoord5 : TEXCOORD5;
				float4 texcoord6 : TEXCOORD6;
			};
			struct fout
			{
				float4 sv_target : SV_Target0;
			};
			// $Globals ConstantBuffers for Vertex Shader
			float _Assemble;
			float _AssembleDistance;
			float _AssembleOffset;
			float _AssembleDif;
			float _AssembleFalloff;
			// $Globals ConstantBuffers for Fragment Shader
			float4 _LightColor0;
			float _RimStrength;
			float4 _Color01;
			float4 _Color21;
			float4 _Color11;
			float4 _Color31;
			float4 _Color00;
			float4 _Color10;
			float4 _Color20;
			float4 _Color30;
			float _SpiralColor;
			float4 _Color41;
			float4 _Color51;
			float4 _Color61;
			float4 _Color71;
			float4 _Color40;
			float4 _Color50;
			float4 _Color60;
			float4 _Color70;
			float _AOUV1;
			float4 _Normal_ST;
			float _NRMUV1;
			float _NRMTriplanar;
			float4 _PaintStrokes_ST;
			float _PaintMaskTriplanar;
			float _OverrideUV1;
			float _GlowMultiplier;
			float4 _GlowRamp_ST;
			float _GlowSpeed;
			// Custom ConstantBuffers for Vertex Shader
			// Custom ConstantBuffers for Fragment Shader
			// Texture params for Vertex Shader
			// Texture params for Fragment Shader
			sampler2D _Normal;
			sampler2D _AmbientOcclusion;
			sampler2D _ColorMask;
			sampler2D _PaintStrokes;
			sampler2D _Override;
			sampler2D _GlowRamp;
			sampler2D _Rim;
			
			// Keywords: DIRECTIONAL
			v2f vert(appdata_full v)
			{
                v2f o;
                float4 tmp0;
                float4 tmp1;
                float4 tmp2;
                float4 tmp3;
                float4 tmp4;
                tmp0.xyz = v.vertex.yyy * unity_ObjectToWorld._m01_m11_m21;
                tmp0.xyz = unity_ObjectToWorld._m00_m10_m20 * v.vertex.xxx + tmp0.xyz;
                tmp0.xyz = unity_ObjectToWorld._m02_m12_m22 * v.vertex.zzz + tmp0.xyz;
                tmp0.xyz = unity_ObjectToWorld._m03_m13_m23 * v.vertex.www + tmp0.xyz;
                tmp0.xyz = tmp0.xyz - _WorldSpaceCameraPos;
                tmp0.x = dot(tmp0.xyz, tmp0.xyz);
                tmp0.x = sqrt(tmp0.x);
                tmp0.x = tmp0.x / _AssembleDistance;
                tmp0.x = log(tmp0.x);
                tmp0.x = tmp0.x * _AssembleFalloff;
                tmp0.x = exp(tmp0.x);
                tmp0.x = 1.0 - tmp0.x;
                tmp0.x = max(tmp0.x, 0.01);
                tmp0.x = min(tmp0.x, 0.99);
                tmp0.y = saturate(_Assemble * 10.0);
                tmp0.z = 1.0 - _Assemble;
                tmp0.y = saturate(-_AssembleDif * tmp0.y + tmp0.z);
                tmp0.xz = tmp0.xz - tmp0.yy;
                tmp0.x = tmp0.x / tmp0.z;
                tmp0.y = tmp0.x < 0.0;
                tmp0.z = tmp0.x > 0.0;
                tmp0.y = uint1(tmp0.z) | uint1(tmp0.y);
                tmp0.z = tmp0.x == 0.0;
                tmp0.x = max(tmp0.x, -20.0);
                tmp0.x = min(tmp0.x, 20.0);
                tmp0.x = saturate(tmp0.x * 500.0064 + -249.5032);
                tmp0.x = 1.0 - tmp0.x;
                tmp1.xyz = tmp0.xxx * v.normal.xyz;
                tmp1.xyz = tmp1.xyz * _AssembleOffset.xxx;
                tmp0.x = uint1(tmp0.z) | uint1(tmp0.y);
                tmp0.xyz = uint3(tmp1.xyz) & uint3(tmp0.xxx);
                tmp0.xyz = tmp0.xyz + v.vertex.xyz;
                tmp1 = tmp0.yyyy * unity_ObjectToWorld._m01_m11_m21_m31;
                tmp1 = unity_ObjectToWorld._m00_m10_m20_m30 * tmp0.xxxx + tmp1;
                tmp0 = unity_ObjectToWorld._m02_m12_m22_m32 * tmp0.zzzz + tmp1;
                tmp1 = tmp0 + unity_ObjectToWorld._m03_m13_m23_m33;
                o.texcoord2 = unity_ObjectToWorld._m03_m13_m23_m33 * v.vertex.wwww + tmp0;
                tmp0 = tmp1.yyyy * unity_MatrixVP._m01_m11_m21_m31;
                tmp0 = unity_MatrixVP._m00_m10_m20_m30 * tmp1.xxxx + tmp0;
                tmp0 = unity_MatrixVP._m02_m12_m22_m32 * tmp1.zzzz + tmp0;
                tmp0 = unity_MatrixVP._m03_m13_m23_m33 * tmp1.wwww + tmp0;
                o.position = tmp0;
                o.texcoord.xy = v.texcoord.xy;
                o.texcoord1.xy = v.texcoord1.xy;
                tmp2.x = dot(v.normal.xyz, unity_WorldToObject._m00_m10_m20);
                tmp2.y = dot(v.normal.xyz, unity_WorldToObject._m01_m11_m21);
                tmp2.z = dot(v.normal.xyz, unity_WorldToObject._m02_m12_m22);
                tmp0.z = dot(tmp2.xyz, tmp2.xyz);
                tmp0.z = rsqrt(tmp0.z);
                tmp2.xyz = tmp0.zzz * tmp2.xyz;
                o.texcoord3.xyz = tmp2.xyz;
                tmp3.xyz = v.tangent.yyy * unity_ObjectToWorld._m01_m11_m21;
                tmp3.xyz = unity_ObjectToWorld._m00_m10_m20 * v.tangent.xxx + tmp3.xyz;
                tmp3.xyz = unity_ObjectToWorld._m02_m12_m22 * v.tangent.zzz + tmp3.xyz;
                tmp0.z = dot(tmp3.xyz, tmp3.xyz);
                tmp0.z = rsqrt(tmp0.z);
                tmp3.xyz = tmp0.zzz * tmp3.xyz;
                o.texcoord4.xyz = tmp3.xyz;
                tmp4.xyz = tmp2.zxy * tmp3.yzx;
                tmp2.xyz = tmp2.yzx * tmp3.zxy + -tmp4.xyz;
                tmp2.xyz = tmp2.xyz * v.tangent.www;
                tmp0.z = dot(tmp2.xyz, tmp2.xyz);
                tmp0.z = rsqrt(tmp0.z);
                o.texcoord5.xyz = tmp0.zzz * tmp2.xyz;
                tmp0.z = tmp1.y * unity_MatrixV._m21;
                tmp0.z = unity_MatrixV._m20 * tmp1.x + tmp0.z;
                tmp0.z = unity_MatrixV._m22 * tmp1.z + tmp0.z;
                tmp0.z = unity_MatrixV._m23 * tmp1.w + tmp0.z;
                o.texcoord6.z = -tmp0.z;
                tmp0.y = tmp0.y * _ProjectionParams.x;
                tmp1.xzw = tmp0.xwy * float3(0.5, 0.5, 0.5);
                o.texcoord6.w = tmp0.w;
                o.texcoord6.xy = tmp1.zz + tmp1.xw;
                return o;
			}
			// Keywords: DIRECTIONAL
			fout frag(v2f inp)
			{
                fout o;
                float4 tmp0;
                float4 tmp1;
                float4 tmp2;
                float4 tmp3;
                float4 tmp4;
                float4 tmp5;
                float4 tmp6;
                float4 tmp7;
                float4 tmp8;
                float4 tmp9;
                float4 tmp10;
                float4 tmp11;
                tmp0.xyz = inp.texcoord2.xyz - _WorldSpaceCameraPos;
                tmp0.x = dot(tmp0.xyz, tmp0.xyz);
                tmp0.x = sqrt(tmp0.x);
                tmp0.x = tmp0.x / _AssembleDistance;
                tmp0.x = log(tmp0.x);
                tmp0.x = tmp0.x * _AssembleFalloff;
                tmp0.x = exp(tmp0.x);
                tmp0.x = 1.0 - tmp0.x;
                tmp0.x = max(tmp0.x, 0.01);
                tmp0.x = min(tmp0.x, 0.99);
                tmp0.y = saturate(_Assemble * 10.0);
                tmp0.z = 1.0 - _Assemble;
                tmp0.y = saturate(-_AssembleDif * tmp0.y + tmp0.z);
                tmp0.xz = tmp0.xz - tmp0.yy;
                tmp0.x = tmp0.x / tmp0.z;
                tmp0.y = tmp0.x < 0.0;
                tmp0.z = tmp0.x > 0.0;
                tmp0.y = uint1(tmp0.z) | uint1(tmp0.y);
                tmp0.z = tmp0.x == 0.0;
                tmp0.x = max(tmp0.x, -20.0);
                tmp0.x = min(tmp0.x, 20.0);
                tmp0.y = uint1(tmp0.z) | uint1(tmp0.y);
                tmp0.x = tmp0.y ? tmp0.x : 20.0;
                tmp0.y = 1.0 - tmp0.x;
                tmp0.z = _ScreenParams.x / _ScreenParams.y;
                tmp1.xy = inp.texcoord6.xy / inp.texcoord6.ww;
                tmp1.yz = tmp1.xy * float2(2.0, 2.0) + float2(-1.0, -1.0);
                tmp1.x = tmp0.z * tmp1.y;
                tmp0.zw = tmp1.xz * float2(32.0, 32.0);
                tmp0.zw = frac(tmp0.zw);
                tmp0.zw = tmp0.zw * float2(2.0, 2.0) + float2(-1.0, -1.0);
                tmp1.x = abs(tmp0.w) - 0.5;
                tmp1.x = -tmp1.x * 2.0 + 1.0;
                tmp1.y = 1.0 - abs(tmp0.z);
                tmp1.x = -tmp1.x * tmp1.y + 1.0;
                tmp1.y = abs(tmp0.w) > 0.5;
                tmp0.z = dot(abs(tmp0.xy), abs(tmp0.xy));
                tmp0.z = saturate(tmp1.y ? tmp1.x : tmp0.z);
                tmp0.zw = tmp0.zz * float2(-0.1, -0.1) + float2(0.55, 0.05);
                tmp1.x = tmp0.z > 0.5;
                tmp0.w = -tmp0.w * 2.0 + 1.0;
                tmp1.yz = inp.texcoord1.xy - inp.texcoord.xy;
                tmp2.xy = _AOUV1.xx * tmp1.yz + inp.texcoord.xy;
                tmp2 = tex2D(_AmbientOcclusion, tmp2.xy);
                tmp2.yz = float2(1.0, 1.0) - tmp2.xw;
                tmp0.w = -tmp0.w * tmp2.y + 1.0;
                tmp0.z = dot(tmp2.xy, tmp0.xy);
                tmp0.z = saturate(tmp1.x ? tmp0.w : tmp0.z);
                tmp0.zw = tmp0.zz * float2(-0.4, -0.4) + float2(0.7, 0.2);
                tmp0.w = -tmp0.w * 2.0 + 1.0;
                tmp0.y = -tmp0.w * tmp0.y + 1.0;
                tmp0.x = dot(tmp0.xy, tmp0.xy);
                tmp0.z = tmp0.z > 0.5;
                tmp0.x = saturate(tmp0.z ? tmp0.y : tmp0.x);
                tmp0.y = tmp0.x - 0.5;
                tmp0.x = tmp0.x * -2.0 + 2.0;
                tmp0.x = min(tmp0.x, 1.0);
                tmp0.y = tmp0.y < 0.0;
                if (tmp0.y) {
                    discard;
                }
                tmp0.yz = inp.texcoord2.zx * _PaintStrokes_ST.xy + _PaintStrokes_ST.zw;
                tmp3 = tex2D(_PaintStrokes, tmp0.yz);
                tmp4 = inp.texcoord2.xyyz * _PaintStrokes_ST + _PaintStrokes_ST;
                tmp5 = tex2D(_PaintStrokes, tmp4.zw);
                tmp4 = tex2D(_PaintStrokes, tmp4.xy);
                tmp0.y = tmp5.x - tmp4.x;
                tmp0.z = dot(inp.texcoord3.xyz, inp.texcoord3.xyz);
                tmp0.z = rsqrt(tmp0.z);
                tmp3.yzw = tmp0.zzz * inp.texcoord3.xyz;
                tmp0.y = abs(tmp3.y) * tmp0.y + tmp4.x;
                tmp0.z = tmp3.x - tmp0.y;
                tmp0.y = abs(tmp3.z) * tmp0.z + tmp0.y;
                tmp0.z = tmp4.x - tmp0.y;
                tmp4.x = abs(tmp3.w) * tmp0.z + tmp0.y;
                tmp0.yz = inp.texcoord2.zx * _PaintStrokes_ST.xy;
                tmp5 = tmp0.yzyz * float4(0.9, 0.9, 1.1, 1.1) + _PaintStrokes_ST;
                tmp0.yz = tmp0.yz * float2(0.65, 0.65) + _PaintStrokes_ST.zw;
                tmp6 = tex2D(_PaintStrokes, tmp0.yz);
                tmp7 = tex2D(_PaintStrokes, tmp5.xy);
                tmp5 = tex2D(_PaintStrokes, tmp5.zw);
                tmp8 = inp.texcoord2.xyyz * _PaintStrokes_ST;
                tmp9 = tmp8 * float4(0.9, 0.9, 0.9, 0.9) + _PaintStrokes_ST;
                tmp10 = tex2D(_PaintStrokes, tmp9.zw);
                tmp9 = tex2D(_PaintStrokes, tmp9.xy);
                tmp0.y = tmp10.y - tmp9.y;
                tmp0.y = abs(tmp3.y) * tmp0.y + tmp9.y;
                tmp0.z = tmp7.y - tmp0.y;
                tmp0.y = abs(tmp3.z) * tmp0.z + tmp0.y;
                tmp0.z = tmp9.y - tmp0.y;
                tmp4.y = abs(tmp3.w) * tmp0.z + tmp0.y;
                tmp7 = tmp8 * float4(1.1, 1.1, 1.1, 1.1) + _PaintStrokes_ST;
                tmp8 = tmp8 * float4(0.55, 0.55, 0.45, 0.45) + _PaintStrokes_ST;
                tmp9 = tex2D(_PaintStrokes, tmp7.zw);
                tmp7 = tex2D(_PaintStrokes, tmp7.xy);
                tmp0.y = tmp9.y - tmp7.y;
                tmp0.y = abs(tmp3.y) * tmp0.y + tmp7.y;
                tmp0.z = tmp5.y - tmp0.y;
                tmp0.y = abs(tmp3.z) * tmp0.z + tmp0.y;
                tmp0.z = tmp7.y - tmp0.y;
                tmp4.z = abs(tmp3.w) * tmp0.z + tmp0.y;
                tmp0.yzw = float3(1.0, 1.0, 1.0) - tmp4.xyz;
                tmp5 = tex2D(_PaintStrokes, tmp8.zw);
                tmp7 = tex2D(_PaintStrokes, tmp8.xy);
                tmp5.xyz = tmp5.xyz - tmp7.xyz;
                tmp5.xyz = abs(tmp3.yyy) * tmp5.xyz + tmp7.xyz;
                tmp6.xyz = tmp6.xyz - tmp5.xyz;
                tmp5.xyz = abs(tmp3.zzz) * tmp6.xyz + tmp5.xyz;
                tmp6.xyz = tmp7.xyz - tmp5.xyz;
                tmp5.xyz = abs(tmp3.www) * tmp6.xyz + tmp5.xyz;
                tmp6.xyz = tmp5.xyz - float3(0.5, 0.5, 0.5);
                tmp6.xyz = -tmp6.xyz * float3(2.0, 2.0, 2.0) + float3(1.0, 1.0, 1.0);
                tmp0.yzw = -tmp6.xyz * tmp0.yzw + float3(1.0, 1.0, 1.0);
                tmp4.xyz = tmp4.xyz * tmp5.xyz;
                tmp5.xyz = tmp5.xyz > float3(0.5, 0.5, 0.5);
                tmp4.xyz = tmp4.xyz + tmp4.xyz;
                tmp0.yzw = saturate(tmp5.xyz ? tmp0.yzw : tmp4.xyz);
                tmp1.xw = _NRMUV1.xx * tmp1.yz + inp.texcoord.xy;
                tmp1.yz = _OverrideUV1.xx * tmp1.yz + inp.texcoord.xy;
                tmp4 = tex2D(_Override, tmp1.yz);
                tmp1.yz = tmp1.xw * _PaintStrokes_ST.xy + _PaintStrokes_ST.zw;
                tmp1.xw = tmp1.xw * _Normal_ST.xy + _Normal_ST.zw;
                tmp5 = tex2D(_Normal, tmp1.xw);
                tmp1 = tex2D(_PaintStrokes, tmp1.yz);
                tmp0.yzw = tmp0.yzw - tmp1.xyz;
                tmp0.yzw = _PaintMaskTriplanar.xxx * tmp0.yzw + tmp1.xyz;
                tmp1.xy = tmp0.yw * float2(0.3, 0.2) + float2(0.35, 0.4);
                tmp0.yzw = tmp0.yzw - float3(0.5, 0.5, 0.5);
                tmp1.zw = inp.texcoord2.zx * _Normal_ST.xy + _Normal_ST.zw;
                tmp6 = tex2D(_Normal, tmp1.zw);
                tmp6.x = tmp6.w * tmp6.x;
                tmp6.xy = tmp6.xy * float2(2.0, 2.0) + float2(-1.0, -1.0);
                tmp1.z = dot(tmp6.xy, tmp6.xy);
                tmp1.z = min(tmp1.z, 1.0);
                tmp1.z = 1.0 - tmp1.z;
                tmp6.z = sqrt(tmp1.z);
                tmp7 = inp.texcoord2.xyyz * _Normal_ST + _Normal_ST;
                tmp8 = tex2D(_Normal, tmp7.zw);
                tmp7 = tex2D(_Normal, tmp7.xy);
                tmp8.x = tmp8.w * tmp8.x;
                tmp8.xy = tmp8.xy * float2(2.0, 2.0) + float2(-1.0, -1.0);
                tmp1.z = dot(tmp8.xy, tmp8.xy);
                tmp1.z = min(tmp1.z, 1.0);
                tmp1.z = 1.0 - tmp1.z;
                tmp8.z = sqrt(tmp1.z);
                tmp7.x = tmp7.w * tmp7.x;
                tmp7.xy = tmp7.xy * float2(2.0, 2.0) + float2(-1.0, -1.0);
                tmp1.z = dot(tmp7.xy, tmp7.xy);
                tmp1.z = min(tmp1.z, 1.0);
                tmp1.z = 1.0 - tmp1.z;
                tmp7.z = sqrt(tmp1.z);
                tmp8.xyz = tmp8.xyz - tmp7.xyz;
                tmp8.xyz = abs(tmp3.yyy) * tmp8.xyz + tmp7.xyz;
                tmp6.xyz = tmp6.xyz - tmp8.xyz;
                tmp6.xyz = abs(tmp3.zzz) * tmp6.xyz + tmp8.xyz;
                tmp7.xyz = tmp7.xyz - tmp6.xyz;
                tmp6.xyz = abs(tmp3.www) * tmp7.xyz + tmp6.xyz;
                tmp5.x = tmp5.w * tmp5.x;
                tmp5.xy = tmp5.xy * float2(2.0, 2.0) + float2(-1.0, -1.0);
                tmp1.z = dot(tmp5.xy, tmp5.xy);
                tmp1.z = min(tmp1.z, 1.0);
                tmp1.z = 1.0 - tmp1.z;
                tmp5.z = sqrt(tmp1.z);
                tmp6.xyz = tmp6.xyz - tmp5.xyz;
                tmp5.xyz = _NRMTriplanar.xxx * tmp6.xyz + tmp5.xyz;
                tmp6.xyz = tmp5.yyy * inp.texcoord5.xyz;
                tmp5.xyw = tmp5.xxx * inp.texcoord4.xyz + tmp6.xyz;
                tmp3.xyz = tmp5.zzz * tmp3.yzw + tmp5.xyw;
                tmp1.z = dot(tmp3.xyz, tmp3.xyz);
                tmp1.z = rsqrt(tmp1.z);
                tmp3.xyz = tmp1.zzz * tmp3.xyz;
                tmp5.xyz = _WorldSpaceCameraPos - inp.texcoord2.xyz;
                tmp1.z = dot(tmp5.xyz, tmp5.xyz);
                tmp1.z = rsqrt(tmp1.z);
                tmp6.xyz = tmp1.zzz * tmp5.xyz;
                tmp1.w = dot(tmp3.xyz, tmp6.xyz);
                tmp1.w = max(tmp1.w, 0.0);
                tmp1.w = 1.0 - tmp1.w;
                tmp2.y = log(tmp1.w);
                tmp6 = _Color00 - _Color30;
                tmp7 = tex2D(_ColorMask, inp.texcoord.xy);
                tmp6 = tmp7.xxxx * tmp6 + _Color30;
                tmp8 = _Color10 - tmp6;
                tmp6 = tmp7.yyyy * tmp8 + tmp6;
                tmp8 = _Color20 - tmp6;
                tmp6 = tmp7.zzzz * tmp8 + tmp6;
                tmp8 = _Color40 - tmp6;
                tmp9.xyz = saturate(tmp7.xyz * float3(1.49925, 1.49925, 1.49925) + float3(-0.4992504, -0.4992504, -0.4992504));
                tmp2.w = tmp9.y * tmp9.x;
                tmp2.w = tmp9.z * tmp2.w;
                tmp9.xyz = tmp9.xxy * tmp9.zyz + -tmp2.www;
                tmp6 = tmp9.xxxx * tmp8 + tmp6;
                tmp8 = _Color50 - tmp6;
                tmp6 = tmp9.yyyy * tmp8 + tmp6;
                tmp8 = _Color60 - tmp6;
                tmp6 = tmp9.zzzz * tmp8 + tmp6;
                tmp8 = _Color70 - tmp6;
                tmp6 = tmp2.wwww * tmp8 + tmp6;
                tmp3.w = tmp6.x * 2.5 + 1.5;
                tmp2.y = tmp2.y * tmp3.w;
                tmp2.y = exp(tmp2.y);
                tmp2.y = tmp2.y * tmp2.y;
                tmp2.y = min(tmp2.y, 1.0);
                tmp3.w = dot(tmp1.xy, tmp2.xy);
                tmp8.xy = float2(1.0, 1.0) - tmp1.xy;
                tmp1.x = tmp2.y - 0.5;
                tmp2.y = tmp2.y > 0.5;
                tmp1.x = -tmp1.x * 2.0 + 1.0;
                tmp1.x = -tmp1.x * tmp8.x + 1.0;
                tmp1.x = saturate(tmp2.y ? tmp1.x : tmp3.w);
                tmp2.y = saturate(tmp3.y);
                tmp2.y = abs(tmp3.x) + tmp2.y;
                tmp2.y = abs(tmp3.z) + tmp2.y;
                tmp1.x = tmp1.x * tmp2.y;
                tmp10 = _Color01 - _Color31;
                tmp10 = tmp7.xxxx * tmp10 + _Color31;
                tmp11 = _Color11 - tmp10;
                tmp10 = tmp7.yyyy * tmp11 + tmp10;
                tmp11 = _Color21 - tmp10;
                tmp10 = tmp7.zzzz * tmp11 + tmp10;
                tmp2.y = 1.0 - tmp7.w;
                tmp7 = _Color41 - tmp10;
                tmp7 = tmp9.xxxx * tmp7 + tmp10;
                tmp10 = _Color51 - tmp7;
                tmp7 = tmp9.yyyy * tmp10 + tmp7;
                tmp10 = _Color61 - tmp7;
                tmp7 = tmp9.zzzz * tmp10 + tmp7;
                tmp9 = _Color71 - tmp7;
                tmp7 = tmp2.wwww * tmp9 + tmp7;
                tmp8.xz = tmp7.xx + float2(1.0, 2.0);
                tmp1.x = dot(tmp1.xy, tmp8.xy);
                tmp2.w = dot(_WorldSpaceLightPos0.xyz, _WorldSpaceLightPos0.xyz);
                tmp2.w = rsqrt(tmp2.w);
                tmp9.xyz = tmp2.www * _WorldSpaceLightPos0.xyz;
                tmp5.xyz = tmp5.xyz * tmp1.zzz + tmp9.xyz;
                tmp1.z = dot(tmp3.xyz, tmp9.xyz);
                tmp2.w = dot(tmp5.xyz, tmp5.xyz);
                tmp2.w = rsqrt(tmp2.w);
                tmp5.xyz = tmp2.www * tmp5.xyz;
                tmp2.w = dot(tmp5.xyz, tmp3.xyz);
                tmp2.w = max(tmp2.w, 0.0);
                tmp2.w = log(tmp2.w);
                tmp5.xyz = tmp7.xxx * float3(8.0, 0.75, -0.1) + float3(-1.0, 0.25, 0.5);
                tmp3.w = exp(tmp5.x);
                tmp3.w = tmp2.w * tmp3.w;
                tmp2.w = tmp2.w * 64.0;
                tmp2.w = exp(tmp2.w);
                tmp9.xyz = tmp2.www * _LightColor0.xyz;
                tmp9.xyz = tmp7.xxx * tmp9.xyz;
                tmp2.w = exp(tmp3.w);
                tmp3.w = tmp7.x + tmp7.x;
                tmp3.w = saturate(tmp5.y * tmp3.w);
                tmp2.w = tmp2.w * tmp3.w;
                tmp5.xy = tmp7.xx * float2(0.75, 3.0);
                tmp2.w = saturate(tmp2.w * tmp5.y);
                tmp3.w = max(tmp1.z, 0.0);
                tmp8.xw = tmp3.ww * float2(1.666667, 20.0) + float2(-0.3333333, -3.0);
                tmp5.w = max(tmp8.w, 0.0);
                tmp8.x = saturate(tmp8.x);
                tmp5.w = min(tmp5.w, 0.8);
                tmp5.w = tmp5.w + tmp8.x;
                tmp3.w = tmp3.w * tmp2.w + tmp5.w;
                tmp1.x = tmp1.x + tmp3.w;
                tmp1.x = tmp2.x * tmp1.x;
                tmp3.w = dot(_LightColor0.xyz, float3(0.3, 0.59, 0.11));
                tmp5.w = -tmp1.x * tmp3.w + tmp2.x;
                tmp1.x = tmp1.x * tmp3.w;
                tmp1.x = tmp6.x * tmp5.w + tmp1.x;
                tmp3.w = tmp2.x * 0.5 + tmp2.w;
                tmp3.w = tmp3.w - tmp1.x;
                tmp3.w = tmp6.x * tmp3.w + tmp1.x;
                tmp1.x = saturate(tmp1.x);
                tmp10.xy = tmp3.ww * float2(5.0, 2.666667);
                tmp10.xy = saturate(tmp10.xy);
                tmp8.xw = saturate(tmp3.ww * float2(-1.111111, -2.181818) + float2(1.111111, 1.2));
                tmp3.w = log(tmp3.w);
                tmp8.xw = tmp8.xw * tmp10.xy;
                tmp5.xy = tmp5.yx * tmp8.wx;
                tmp5.x = saturate(tmp5.x);
                tmp5.y = log(tmp5.y);
                tmp5.y = tmp5.y * tmp8.z;
                tmp5.y = exp(tmp5.y);
                tmp5.y = min(tmp5.y, 1.0);
                tmp5.w = tmp7.x * 2.0 + 1.0;
                tmp3.w = tmp3.w * tmp5.w;
                tmp3.w = exp(tmp3.w);
                tmp3.w = min(tmp3.w, 1.0);
                tmp3.w = tmp3.w - tmp5.x;
                tmp3.w = max(tmp3.w, 0.0);
                tmp3.w = tmp5.y + tmp3.w;
                tmp3.w = min(tmp3.w, 1.0);
                tmp5.xw = tmp3.ww * float2(1.49925, 3.003003);
                tmp5.xw = min(tmp5.xw, float2(1.0, 1.0));
                tmp7.yzw = tmp7.yzw - tmp6.yzw;
                tmp8.xzw = tmp7.xxx * float3(1.6, -0.1, 0.3) + float3(-0.8, 0.6, 1.2);
                tmp6.yzw = tmp1.xxx * tmp7.yzw + tmp6.yzw;
                tmp1.x = saturate(tmp2.y + tmp6.x);
                tmp4.xyz = tmp4.xyz - tmp6.yzw;
                tmp4.xyz = tmp4.www * tmp4.xyz + tmp6.yzw;
                tmp6.xy = tmp4.zy;
                tmp7.xy = tmp4.yz - tmp6.xy;
                tmp4.w = tmp6.y >= tmp4.z;
                tmp4.w = tmp4.w ? 1.0 : 0.0;
                tmp6.zw = float2(-1.0, 0.6666667);
                tmp7.zw = float2(1.0, -1.0);
                tmp6 = tmp4.wwww * tmp7.xywz + tmp6.xywz;
                tmp4.w = tmp4.x >= tmp6.x;
                tmp4.w = tmp4.w ? 1.0 : 0.0;
                tmp7.z = tmp6.w;
                tmp6.w = tmp4.x;
                tmp7.xyw = tmp6.wyx;
                tmp7 = tmp7 - tmp6;
                tmp6 = tmp4.wwww * tmp7 + tmp6;
                tmp4.w = min(tmp6.y, tmp6.w);
                tmp4.w = tmp6.x - tmp4.w;
                tmp7.x = tmp4.w * 6.0 + 0.0;
                tmp6.y = tmp6.w - tmp6.y;
                tmp6.y = tmp6.y / tmp7.x;
                tmp6.y = tmp6.y + tmp6.z;
                tmp7.xyz = abs(tmp6.yyy) + float3(-0.05, -0.3833334, 0.2833333);
                tmp6.yzw = abs(tmp6.yyy) + float3(0.01, -0.3233334, 0.3433333);
                tmp6.yzw = frac(tmp6.yzw);
                tmp6.yzw = -tmp6.yzw * float3(2.0, 2.0, 2.0) + float3(1.0, 1.0, 1.0);
                tmp6.yzw = saturate(abs(tmp6.yzw) * float3(3.0, 3.0, 3.0) + float3(-1.0, -1.0, -1.0));
                tmp6.yzw = tmp6.yzw - float3(1.0, 1.0, 1.0);
                tmp7.xyz = frac(tmp7.xyz);
                tmp7.xyz = -tmp7.xyz * float3(2.0, 2.0, 2.0) + float3(1.0, 1.0, 1.0);
                tmp7.xyz = saturate(abs(tmp7.xyz) * float3(3.0, 3.0, 3.0) + float3(-1.0, -1.0, -1.0));
                tmp7.xyz = tmp7.xyz - float3(1.0, 1.0, 1.0);
                tmp7.w = tmp6.x + 0.0;
                tmp4.w = tmp4.w / tmp7.w;
                tmp7.xyz = tmp4.www * tmp7.xyz + float3(1.0, 1.0, 1.0);
                tmp6.yzw = tmp4.www * tmp6.yzw + float3(1.0, 1.0, 1.0);
                tmp10.xyz = tmp6.xxx * tmp7.xyz;
                tmp4.w = dot(tmp10.xyz, float3(0.3, 0.59, 0.11));
                tmp11.xyz = -tmp7.xyz * tmp6.xxx + tmp4.www;
                tmp7.xyz = tmp7.xyz * tmp6.xxx + -tmp11.xyz;
                tmp10.xyz = tmp11.xyz * float3(0.2, 0.2, 0.2) + tmp10.xyz;
                tmp11.xyz = -tmp7.xyz * tmp5.zzz + tmp4.xyz;
                tmp7.xyz = tmp5.zzz * tmp7.xyz;
                tmp11.xyz = tmp5.xxx * tmp11.xyz + tmp7.xyz;
                tmp11.xyz = -tmp10.xyz * tmp8.zzz + tmp11.xyz;
                tmp10.xyz = tmp8.zzz * tmp10.xyz;
                tmp5.xzw = tmp5.www * tmp11.xyz + tmp10.xyz;
                tmp10.xyz = tmp6.xxx * tmp6.yzw;
                tmp4.w = dot(tmp10.xyz, float3(0.3, 0.59, 0.11));
                tmp6.xyz = -tmp6.yzw * tmp6.xxx + tmp4.www;
                tmp6.xyz = tmp6.xyz * float3(0.05, 0.05, 0.05) + tmp10.xyz;
                tmp6.xyz = saturate(tmp8.www * tmp6.xyz);
                tmp8.x = saturate(tmp8.x);
                tmp6.xyz = tmp6.xyz - tmp4.xyz;
                tmp4.w = tmp3.w * 1.49925 + -0.4992504;
                tmp4.w = max(tmp4.w, 0.0);
                tmp4.xyz = tmp4.www * tmp6.xyz + tmp4.xyz;
                tmp4.xyz = tmp4.xyz - tmp5.xzw;
                tmp4.xyz = tmp3.www * tmp4.xyz + tmp5.xzw;
                tmp3.w = tmp4.y >= tmp4.z;
                tmp3.w = tmp3.w ? 1.0 : 0.0;
                tmp6.xy = tmp4.zy;
                tmp10.xy = tmp4.yz - tmp6.xy;
                tmp6.zw = float2(-1.0, 0.6666667);
                tmp10.zw = float2(1.0, -1.0);
                tmp6 = tmp3.wwww * tmp10.xywz + tmp6.xywz;
                tmp3.w = tmp4.x >= tmp6.x;
                tmp3.w = tmp3.w ? 1.0 : 0.0;
                tmp10.z = tmp6.w;
                tmp6.w = tmp4.x;
                tmp10.xyw = tmp6.wyx;
                tmp10 = tmp10 - tmp6;
                tmp6 = tmp3.wwww * tmp10 + tmp6;
                tmp3.w = min(tmp6.y, tmp6.w);
                tmp3.w = tmp6.x - tmp3.w;
                tmp4.w = tmp3.w * 6.0 + 0.0;
                tmp5.x = tmp6.w - tmp6.y;
                tmp4.w = tmp5.x / tmp4.w;
                tmp4.w = tmp4.w + tmp6.z;
                tmp5.xzw = abs(tmp4.www) + float3(-0.125, -0.4583333, 0.2083333);
                tmp5.xzw = frac(tmp5.xzw);
                tmp5.xzw = -tmp5.xzw * float3(2.0, 2.0, 2.0) + float3(1.0, 1.0, 1.0);
                tmp5.xzw = saturate(abs(tmp5.xzw) * float3(3.0, 3.0, 3.0) + float3(-1.0, -1.0, -1.0));
                tmp5.xzw = tmp5.xzw - float3(1.0, 1.0, 1.0);
                tmp4.w = tmp6.x + 0.0;
                tmp3.w = tmp3.w / tmp4.w;
                tmp5.xzw = tmp3.www * tmp5.xzw + float3(1.0, 1.0, 1.0);
                tmp6.yzw = tmp6.xxx * tmp5.xzw;
                tmp3.w = dot(tmp6.xyz, float3(0.3, 0.59, 0.11));
                tmp5.xzw = -tmp5.xzw * tmp6.xxx + tmp3.www;
                tmp5.xzw = tmp5.xzw * float3(0.1, 0.1, 0.1) + tmp6.yzw;
                tmp5.xzw = tmp5.xzw - tmp4.xyz;
                tmp4.xyz = tmp5.yyy * tmp5.xzw + tmp4.xyz;
                tmp5.xyz = tmp4.xyz * float3(1.333, 1.333, 1.333);
                tmp3.w = dot(tmp5.xyz, float3(0.3, 0.59, 0.11));
                tmp4.xyz = -tmp4.xyz * float3(1.333, 1.333, 1.333) + tmp3.www;
                tmp4.xyz = tmp4.xyz * tmp8.xxx;
                tmp4.xyz = tmp2.www * tmp4.xyz + tmp5.xyz;
                tmp2.w = tmp4.y >= tmp4.z;
                tmp2.w = tmp2.w ? 1.0 : 0.0;
                tmp5.xy = tmp4.zy;
                tmp6.xy = tmp4.yz - tmp5.xy;
                tmp5.zw = float2(-1.0, 0.6666667);
                tmp6.zw = float2(1.0, -1.0);
                tmp5 = tmp2.wwww * tmp6.xywz + tmp5.xywz;
                tmp2.w = tmp4.x >= tmp5.x;
                tmp2.w = tmp2.w ? 1.0 : 0.0;
                tmp6.z = tmp5.w;
                tmp5.w = tmp4.x;
                tmp6.xyw = tmp5.wyx;
                tmp6 = tmp6 - tmp5;
                tmp5 = tmp2.wwww * tmp6 + tmp5;
                tmp2.w = min(tmp5.y, tmp5.w);
                tmp2.w = tmp5.x - tmp2.w;
                tmp3.w = tmp2.w * 6.0 + 0.0;
                tmp4.w = tmp5.w - tmp5.y;
                tmp3.w = tmp4.w / tmp3.w;
                tmp3.w = tmp3.w + tmp5.z;
                tmp5.xy = tmp5.xx + float2(0.0, 0.1);
                tmp6.xyz = abs(tmp3.www) + float3(0.0, -0.3333333, 0.3333333);
                tmp6.xyz = frac(tmp6.xyz);
                tmp6.xyz = -tmp6.xyz * float3(2.0, 2.0, 2.0) + float3(1.0, 1.0, 1.0);
                tmp6.xyz = saturate(abs(tmp6.xyz) * float3(3.0, 3.0, 3.0) + float3(-1.0, -1.0, -1.0));
                tmp6.xyz = tmp6.xyz - float3(1.0, 1.0, 1.0);
                tmp2.w = tmp2.w / tmp5.x;
                tmp2.w = tmp2.w - 0.5;
                tmp5.xzw = tmp2.www * tmp6.xyz + float3(1.0, 1.0, 1.0);
                tmp5.xyz = tmp5.xzw * tmp5.yyy + -tmp4.xyz;
                tmp4.xyz = saturate(tmp2.zzz * tmp5.xyz + tmp4.xyz);
                tmp2.z = _Time.y * 6.283;
                tmp2.z = sin(tmp2.z);
                tmp2.zw = tmp2.zz * float2(0.35, 0.05) + float2(0.85, 0.95);
                tmp2.w = tmp2.w - tmp2.z;
                tmp3.w = _SpiralColor * 2.0 + -1.0;
                tmp2.z = abs(tmp3.w) * tmp2.w + tmp2.z;
                tmp5.x = tmp2.x * tmp2.z;
                tmp2.z = _GlowSpeed * _Time.y;
                tmp6.y = frac(tmp2.z);
                tmp6.x = 0.0;
                tmp5.y = _SpiralColor;
                tmp2.zw = tmp5.xy + tmp6.xy;
                tmp2.zw = tmp2.zw * _GlowRamp_ST.xy + _GlowRamp_ST.zw;
                tmp5 = tex2D(_GlowRamp, tmp2.zw);
                tmp2.z = tmp2.y * _GlowMultiplier;
                tmp2.z = tmp2.z * 3.0;
                tmp5.xyz = tmp5.xyz * tmp2.zzz + -tmp4.xyz;
                tmp2.yzw = tmp2.yyy * tmp5.xyz + tmp4.xyz;
                tmp3.w = tmp2.z >= tmp2.w;
                tmp3.w = tmp3.w ? 1.0 : 0.0;
                tmp4.xy = tmp2.wz;
                tmp5.xy = tmp2.zw - tmp4.xy;
                tmp4.zw = float2(-1.0, 0.6666667);
                tmp5.zw = float2(1.0, -1.0);
                tmp4 = tmp3.wwww * tmp5.xywz + tmp4.xywz;
                tmp3.w = tmp2.y >= tmp4.x;
                tmp3.w = tmp3.w ? 1.0 : 0.0;
                tmp5.z = tmp4.w;
                tmp4.w = tmp2.y;
                tmp5.xyw = tmp4.wyx;
                tmp5 = tmp5 - tmp4;
                tmp4 = tmp3.wwww * tmp5 + tmp4;
                tmp3.yw = tmp3.yy * unity_MatrixV._m01_m11;
                tmp3.xy = unity_MatrixV._m00_m10 * tmp3.xx + tmp3.yw;
                tmp3.xy = unity_MatrixV._m02_m12 * tmp3.zz + tmp3.xy;
                tmp3.xy = tmp3.xy * float2(0.5, 0.5) + float2(0.5, 0.5);
                tmp3 = tex2D(_Rim, tmp3.xy);
                tmp3.xyz = tmp2.xxx * tmp3.xyz;
                tmp3.xyz = tmp3.xyz * _RimStrength.xxx;
                tmp5.xyz = glstate_lightmodel_ambient.xyz + glstate_lightmodel_ambient.xyz;
                tmp2.x = dot(tmp5.xyz, float3(0.3, 0.59, 0.11));
                tmp6.xyz = -glstate_lightmodel_ambient.xyz * float3(2.0, 2.0, 2.0) + tmp2.xxx;
                tmp6.xyz = tmp6.xyz * float3(0.5, 0.5, 0.5) + tmp5.xyz;
                tmp8.xzw = tmp3.xyz * tmp6.xyz + float3(-0.5, -0.5, -0.5);
                tmp3.xyz = tmp3.xyz * tmp6.xyz;
                tmp6.xyz = -tmp8.xzw * float3(2.0, 2.0, 2.0) + float3(1.0, 1.0, 1.0);
                tmp6.xyz = -tmp6.xyz * tmp8.yyy + float3(1.0, 1.0, 1.0);
                tmp8.xyz = tmp1.yyy * tmp3.xyz;
                tmp3.xyz = tmp3.xyz > float3(0.5, 0.5, 0.5);
                tmp8.xyz = tmp8.xyz + tmp8.xyz;
                tmp3.xyz = tmp3.xyz ? tmp6.xyz : tmp8.xyz;
                tmp6.xyz = tmp2.yzw * float3(0.1, 0.1, 0.1);
                tmp2.xyz = -tmp6.xyz * tmp5.xyz + tmp2.yzw;
                tmp6.xyz = tmp5.xyz * tmp6.xyz;
                tmp2.xyz = tmp1.xxx * tmp2.xyz + tmp6.xyz;
                tmp2.xyz = tmp3.xyz + tmp2.xyz;
                tmp1.y = tmp0.x * 2.0 + -1.0;
                tmp1.y = tmp1.w * tmp1.w + tmp1.y;
                tmp3.xyz = tmp1.yyy * float3(0.7768763, 0.0, -0.4042597) + float3(0.0, 1.0, 0.6689656);
                tmp1.y = tmp0.x * 1.5;
                tmp2.xyz = tmp3.xyz * tmp1.yyy + tmp2.xyz;
                tmp1.y = min(tmp4.y, tmp4.w);
                tmp1.y = tmp4.x - tmp1.y;
                tmp1.w = tmp1.y * 6.0 + 0.0;
                tmp2.w = tmp4.w - tmp4.y;
                tmp1.w = tmp2.w / tmp1.w;
                tmp1.w = tmp1.w + tmp4.z;
                tmp0.y = tmp0.y * 0.04 + abs(tmp1.w);
                tmp4.yzw = tmp0.yyy + float3(0.0, -0.3333333, 0.3333333);
                tmp4.yzw = frac(tmp4.yzw);
                tmp4.yzw = -tmp4.yzw * float3(2.0, 2.0, 2.0) + float3(1.0, 1.0, 1.0);
                tmp4.yzw = saturate(abs(tmp4.yzw) * float3(3.0, 3.0, 3.0) + float3(-1.0, -1.0, -1.0));
                tmp4.yzw = tmp4.yzw - float3(1.0, 1.0, 1.0);
                tmp0.y = tmp4.x + 0.0;
                tmp0.w = tmp0.w * 0.075 + tmp4.x;
                tmp0.y = tmp1.y / tmp0.y;
                tmp0.y = tmp0.z * 0.05 + tmp0.y;
                tmp4.xyz = tmp0.yyy * tmp4.yzw + float3(1.0, 1.0, 1.0);
                tmp0.yzw = tmp0.www * tmp4.xyz;
                tmp0.yzw = tmp1.xxx * -tmp0.yzw + tmp0.yzw;
                tmp1.xyw = tmp3.xyz - tmp0.yzw;
                tmp0.xyz = tmp0.xxx * tmp1.xyw + tmp0.yzw;
                tmp1.xyw = tmp7.xyz * float3(0.5, 0.5, 0.5);
                tmp3.xyz = -tmp7.xyz * float3(0.5, 0.5, 0.5) + float3(1.0, 1.0, 1.0);
                tmp1.xyz = tmp1.zzz * tmp3.xyz + tmp1.xyw;
                tmp1.xyz = max(tmp1.xyz, float3(0.0, 0.0, 0.0));
                tmp1.xyz = tmp1.xyz * _LightColor0.xyz + tmp5.xyz;
                tmp0.xyz = tmp1.xyz * tmp0.xyz + tmp9.xyz;
                o.sv_target.xyz = tmp2.xyz + tmp0.xyz;
                o.sv_target.w = 1.0;
                return o;
			}
			ENDCG
		}
		Pass {
			Name "FORWARD_DELTA"
			Tags { "DisableBatching" = "true" "LIGHTMODE" = "FORWARDADD" "PreviewType" = "Plane" "RenderType" = "Opaque" "SHADOWSUPPORT" = "true" }
			Blend One One, One One
			GpuProgramID 123365
			CGPROGRAM
			#pragma vertex vert
			#pragma fragment frag
			
			#include "UnityCG.cginc"
			struct v2f
			{
				float4 position : SV_POSITION0;
				float2 texcoord : TEXCOORD0;
				float2 texcoord1 : TEXCOORD1;
				float4 texcoord2 : TEXCOORD2;
				float3 texcoord3 : TEXCOORD3;
				float3 texcoord4 : TEXCOORD4;
				float3 texcoord5 : TEXCOORD5;
				float4 texcoord6 : TEXCOORD6;
				float3 texcoord7 : TEXCOORD7;
			};
			struct fout
			{
				float4 sv_target : SV_Target0;
			};
			// $Globals ConstantBuffers for Vertex Shader
			float4x4 unity_WorldToLight;
			float _Assemble;
			float _AssembleDistance;
			float _AssembleOffset;
			float _AssembleDif;
			float _AssembleFalloff;
			// $Globals ConstantBuffers for Fragment Shader
			float4 _LightColor0;
			float4 _Color01;
			float4 _Color21;
			float4 _Color11;
			float4 _Color31;
			float4 _Color00;
			float4 _Color10;
			float4 _Color20;
			float4 _Color30;
			float _SpiralColor;
			float4 _Color41;
			float4 _Color51;
			float4 _Color61;
			float4 _Color71;
			float4 _Color40;
			float4 _Color50;
			float4 _Color60;
			float4 _Color70;
			float _AOUV1;
			float4 _Normal_ST;
			float _NRMUV1;
			float _NRMTriplanar;
			float4 _PaintStrokes_ST;
			float _PaintMaskTriplanar;
			float _OverrideUV1;
			float _GlowMultiplier;
			float4 _GlowRamp_ST;
			float _GlowSpeed;
			// Custom ConstantBuffers for Vertex Shader
			// Custom ConstantBuffers for Fragment Shader
			// Texture params for Vertex Shader
			// Texture params for Fragment Shader
			sampler2D _Normal;
			sampler2D _AmbientOcclusion;
			sampler2D _LightTexture0;
			sampler2D _ColorMask;
			sampler2D _PaintStrokes;
			sampler2D _Override;
			sampler2D _GlowRamp;
			
			// Keywords: POINT
			v2f vert(appdata_full v)
			{
                v2f o;
                float4 tmp0;
                float4 tmp1;
                float4 tmp2;
                float4 tmp3;
                float4 tmp4;
                float4 tmp5;
                tmp0.xyz = v.vertex.yyy * unity_ObjectToWorld._m01_m11_m21;
                tmp0.xyz = unity_ObjectToWorld._m00_m10_m20 * v.vertex.xxx + tmp0.xyz;
                tmp0.xyz = unity_ObjectToWorld._m02_m12_m22 * v.vertex.zzz + tmp0.xyz;
                tmp0.xyz = unity_ObjectToWorld._m03_m13_m23 * v.vertex.www + tmp0.xyz;
                tmp0.xyz = tmp0.xyz - _WorldSpaceCameraPos;
                tmp0.x = dot(tmp0.xyz, tmp0.xyz);
                tmp0.x = sqrt(tmp0.x);
                tmp0.x = tmp0.x / _AssembleDistance;
                tmp0.x = log(tmp0.x);
                tmp0.x = tmp0.x * _AssembleFalloff;
                tmp0.x = exp(tmp0.x);
                tmp0.x = 1.0 - tmp0.x;
                tmp0.x = max(tmp0.x, 0.01);
                tmp0.x = min(tmp0.x, 0.99);
                tmp0.y = saturate(_Assemble * 10.0);
                tmp0.z = 1.0 - _Assemble;
                tmp0.y = saturate(-_AssembleDif * tmp0.y + tmp0.z);
                tmp0.xz = tmp0.xz - tmp0.yy;
                tmp0.x = tmp0.x / tmp0.z;
                tmp0.y = tmp0.x < 0.0;
                tmp0.z = tmp0.x > 0.0;
                tmp0.y = uint1(tmp0.z) | uint1(tmp0.y);
                tmp0.z = tmp0.x == 0.0;
                tmp0.x = max(tmp0.x, -20.0);
                tmp0.x = min(tmp0.x, 20.0);
                tmp0.x = saturate(tmp0.x * 500.0064 + -249.5032);
                tmp0.x = 1.0 - tmp0.x;
                tmp1.xyz = tmp0.xxx * v.normal.xyz;
                tmp1.xyz = tmp1.xyz * _AssembleOffset.xxx;
                tmp0.x = uint1(tmp0.z) | uint1(tmp0.y);
                tmp0.xyz = uint3(tmp1.xyz) & uint3(tmp0.xxx);
                tmp0.xyz = tmp0.xyz + v.vertex.xyz;
                tmp1 = tmp0.yyyy * unity_ObjectToWorld._m01_m11_m21_m31;
                tmp1 = unity_ObjectToWorld._m00_m10_m20_m30 * tmp0.xxxx + tmp1;
                tmp0 = unity_ObjectToWorld._m02_m12_m22_m32 * tmp0.zzzz + tmp1;
                tmp1 = tmp0 + unity_ObjectToWorld._m03_m13_m23_m33;
                tmp0 = unity_ObjectToWorld._m03_m13_m23_m33 * v.vertex.wwww + tmp0;
                tmp2 = tmp1.yyyy * unity_MatrixVP._m01_m11_m21_m31;
                tmp2 = unity_MatrixVP._m00_m10_m20_m30 * tmp1.xxxx + tmp2;
                tmp2 = unity_MatrixVP._m02_m12_m22_m32 * tmp1.zzzz + tmp2;
                tmp2 = unity_MatrixVP._m03_m13_m23_m33 * tmp1.wwww + tmp2;
                o.position = tmp2;
                o.texcoord.xy = v.texcoord.xy;
                o.texcoord1.xy = v.texcoord1.xy;
                o.texcoord2 = tmp0;
                tmp3.x = dot(v.normal.xyz, unity_WorldToObject._m00_m10_m20);
                tmp3.y = dot(v.normal.xyz, unity_WorldToObject._m01_m11_m21);
                tmp3.z = dot(v.normal.xyz, unity_WorldToObject._m02_m12_m22);
                tmp2.z = dot(tmp3.xyz, tmp3.xyz);
                tmp2.z = rsqrt(tmp2.z);
                tmp3.xyz = tmp2.zzz * tmp3.xyz;
                o.texcoord3.xyz = tmp3.xyz;
                tmp4.xyz = v.tangent.yyy * unity_ObjectToWorld._m01_m11_m21;
                tmp4.xyz = unity_ObjectToWorld._m00_m10_m20 * v.tangent.xxx + tmp4.xyz;
                tmp4.xyz = unity_ObjectToWorld._m02_m12_m22 * v.tangent.zzz + tmp4.xyz;
                tmp2.z = dot(tmp4.xyz, tmp4.xyz);
                tmp2.z = rsqrt(tmp2.z);
                tmp4.xyz = tmp2.zzz * tmp4.xyz;
                o.texcoord4.xyz = tmp4.xyz;
                tmp5.xyz = tmp3.zxy * tmp4.yzx;
                tmp3.xyz = tmp3.yzx * tmp4.zxy + -tmp5.xyz;
                tmp3.xyz = tmp3.xyz * v.tangent.www;
                tmp2.z = dot(tmp3.xyz, tmp3.xyz);
                tmp2.z = rsqrt(tmp2.z);
                o.texcoord5.xyz = tmp2.zzz * tmp3.xyz;
                tmp1.y = tmp1.y * unity_MatrixV._m21;
                tmp1.x = unity_MatrixV._m20 * tmp1.x + tmp1.y;
                tmp1.x = unity_MatrixV._m22 * tmp1.z + tmp1.x;
                tmp1.x = unity_MatrixV._m23 * tmp1.w + tmp1.x;
                o.texcoord6.z = -tmp1.x;
                tmp1.x = tmp2.y * _ProjectionParams.x;
                tmp1.w = tmp1.x * 0.5;
                tmp1.xz = tmp2.xw * float2(0.5, 0.5);
                o.texcoord6.w = tmp2.w;
                o.texcoord6.xy = tmp1.zz + tmp1.xw;
                tmp1.xyz = tmp0.yyy * unity_WorldToLight._m01_m11_m21;
                tmp1.xyz = unity_WorldToLight._m00_m10_m20 * tmp0.xxx + tmp1.xyz;
                tmp0.xyz = unity_WorldToLight._m02_m12_m22 * tmp0.zzz + tmp1.xyz;
                o.texcoord7.xyz = unity_WorldToLight._m03_m13_m23 * tmp0.www + tmp0.xyz;
                return o;
			}
			// Keywords: POINT
			fout frag(v2f inp)
			{
                fout o;
                float4 tmp0;
                float4 tmp1;
                float4 tmp2;
                float4 tmp3;
                float4 tmp4;
                float4 tmp5;
                float4 tmp6;
                float4 tmp7;
                float4 tmp8;
                float4 tmp9;
                float4 tmp10;
                tmp0.xyz = inp.texcoord2.xyz - _WorldSpaceCameraPos;
                tmp0.x = dot(tmp0.xyz, tmp0.xyz);
                tmp0.x = sqrt(tmp0.x);
                tmp0.x = tmp0.x / _AssembleDistance;
                tmp0.x = log(tmp0.x);
                tmp0.x = tmp0.x * _AssembleFalloff;
                tmp0.x = exp(tmp0.x);
                tmp0.x = 1.0 - tmp0.x;
                tmp0.x = max(tmp0.x, 0.01);
                tmp0.x = min(tmp0.x, 0.99);
                tmp0.y = saturate(_Assemble * 10.0);
                tmp0.z = 1.0 - _Assemble;
                tmp0.y = saturate(-_AssembleDif * tmp0.y + tmp0.z);
                tmp0.xz = tmp0.xz - tmp0.yy;
                tmp0.x = tmp0.x / tmp0.z;
                tmp0.y = tmp0.x < 0.0;
                tmp0.z = tmp0.x > 0.0;
                tmp0.y = uint1(tmp0.z) | uint1(tmp0.y);
                tmp0.z = tmp0.x == 0.0;
                tmp0.x = max(tmp0.x, -20.0);
                tmp0.x = min(tmp0.x, 20.0);
                tmp0.y = uint1(tmp0.z) | uint1(tmp0.y);
                tmp0.x = tmp0.y ? tmp0.x : 20.0;
                tmp0.y = 1.0 - tmp0.x;
                tmp0.z = _ScreenParams.x / _ScreenParams.y;
                tmp1.xy = inp.texcoord6.xy / inp.texcoord6.ww;
                tmp1.yz = tmp1.xy * float2(2.0, 2.0) + float2(-1.0, -1.0);
                tmp1.x = tmp0.z * tmp1.y;
                tmp0.zw = tmp1.xz * float2(32.0, 32.0);
                tmp0.zw = frac(tmp0.zw);
                tmp0.zw = tmp0.zw * float2(2.0, 2.0) + float2(-1.0, -1.0);
                tmp1.x = abs(tmp0.w) - 0.5;
                tmp1.x = -tmp1.x * 2.0 + 1.0;
                tmp1.y = 1.0 - abs(tmp0.z);
                tmp1.x = -tmp1.x * tmp1.y + 1.0;
                tmp1.y = abs(tmp0.w) > 0.5;
                tmp0.z = dot(abs(tmp0.xy), abs(tmp0.xy));
                tmp0.z = saturate(tmp1.y ? tmp1.x : tmp0.z);
                tmp0.zw = tmp0.zz * float2(-0.1, -0.1) + float2(0.55, 0.05);
                tmp1.x = tmp0.z > 0.5;
                tmp0.w = -tmp0.w * 2.0 + 1.0;
                tmp1.yz = inp.texcoord1.xy - inp.texcoord.xy;
                tmp2.xy = _AOUV1.xx * tmp1.yz + inp.texcoord.xy;
                tmp2 = tex2D(_AmbientOcclusion, tmp2.xy);
                tmp2.yz = float2(1.0, 1.0) - tmp2.xw;
                tmp0.w = -tmp0.w * tmp2.y + 1.0;
                tmp0.z = dot(tmp2.xy, tmp0.xy);
                tmp0.z = saturate(tmp1.x ? tmp0.w : tmp0.z);
                tmp0.zw = tmp0.zz * float2(-0.4, -0.4) + float2(0.7, 0.2);
                tmp0.w = -tmp0.w * 2.0 + 1.0;
                tmp0.y = -tmp0.w * tmp0.y + 1.0;
                tmp0.x = dot(tmp0.xy, tmp0.xy);
                tmp0.z = tmp0.z > 0.5;
                tmp0.x = saturate(tmp0.z ? tmp0.y : tmp0.x);
                tmp0.y = tmp0.x - 0.5;
                tmp0.x = tmp0.x * -2.0 + 2.0;
                tmp0.x = min(tmp0.x, 1.0);
                tmp0.y = tmp0.y < 0.0;
                if (tmp0.y) {
                    discard;
                }
                tmp0.yz = inp.texcoord2.zx * _PaintStrokes_ST.xy + _PaintStrokes_ST.zw;
                tmp3 = tex2D(_PaintStrokes, tmp0.yz);
                tmp4 = inp.texcoord2.xyyz * _PaintStrokes_ST + _PaintStrokes_ST;
                tmp5 = tex2D(_PaintStrokes, tmp4.zw);
                tmp4 = tex2D(_PaintStrokes, tmp4.xy);
                tmp0.y = tmp5.x - tmp4.x;
                tmp0.z = dot(inp.texcoord3.xyz, inp.texcoord3.xyz);
                tmp0.z = rsqrt(tmp0.z);
                tmp3.yzw = tmp0.zzz * inp.texcoord3.xyz;
                tmp0.y = abs(tmp3.y) * tmp0.y + tmp4.x;
                tmp0.z = tmp3.x - tmp0.y;
                tmp0.y = abs(tmp3.z) * tmp0.z + tmp0.y;
                tmp0.z = tmp4.x - tmp0.y;
                tmp4.x = abs(tmp3.w) * tmp0.z + tmp0.y;
                tmp0.yz = inp.texcoord2.zx * _PaintStrokes_ST.xy;
                tmp5 = tmp0.yzyz * float4(0.9, 0.9, 1.1, 1.1) + _PaintStrokes_ST;
                tmp0.yz = tmp0.yz * float2(0.65, 0.65) + _PaintStrokes_ST.zw;
                tmp6 = tex2D(_PaintStrokes, tmp0.yz);
                tmp7 = tex2D(_PaintStrokes, tmp5.xy);
                tmp5 = tex2D(_PaintStrokes, tmp5.zw);
                tmp8 = inp.texcoord2.xyyz * _PaintStrokes_ST;
                tmp9 = tmp8 * float4(0.9, 0.9, 0.9, 0.9) + _PaintStrokes_ST;
                tmp10 = tex2D(_PaintStrokes, tmp9.zw);
                tmp9 = tex2D(_PaintStrokes, tmp9.xy);
                tmp0.y = tmp10.y - tmp9.y;
                tmp0.y = abs(tmp3.y) * tmp0.y + tmp9.y;
                tmp0.z = tmp7.y - tmp0.y;
                tmp0.y = abs(tmp3.z) * tmp0.z + tmp0.y;
                tmp0.z = tmp9.y - tmp0.y;
                tmp4.y = abs(tmp3.w) * tmp0.z + tmp0.y;
                tmp7 = tmp8 * float4(1.1, 1.1, 1.1, 1.1) + _PaintStrokes_ST;
                tmp8 = tmp8 * float4(0.55, 0.55, 0.45, 0.45) + _PaintStrokes_ST;
                tmp9 = tex2D(_PaintStrokes, tmp7.zw);
                tmp7 = tex2D(_PaintStrokes, tmp7.xy);
                tmp0.y = tmp9.y - tmp7.y;
                tmp0.y = abs(tmp3.y) * tmp0.y + tmp7.y;
                tmp0.z = tmp5.y - tmp0.y;
                tmp0.y = abs(tmp3.z) * tmp0.z + tmp0.y;
                tmp0.z = tmp7.y - tmp0.y;
                tmp4.z = abs(tmp3.w) * tmp0.z + tmp0.y;
                tmp0.yzw = float3(1.0, 1.0, 1.0) - tmp4.xyz;
                tmp5 = tex2D(_PaintStrokes, tmp8.zw);
                tmp7 = tex2D(_PaintStrokes, tmp8.xy);
                tmp5.xyz = tmp5.xyz - tmp7.xyz;
                tmp5.xyz = abs(tmp3.yyy) * tmp5.xyz + tmp7.xyz;
                tmp6.xyz = tmp6.xyz - tmp5.xyz;
                tmp5.xyz = abs(tmp3.zzz) * tmp6.xyz + tmp5.xyz;
                tmp6.xyz = tmp7.xyz - tmp5.xyz;
                tmp5.xyz = abs(tmp3.www) * tmp6.xyz + tmp5.xyz;
                tmp6.xyz = tmp5.xyz - float3(0.5, 0.5, 0.5);
                tmp6.xyz = -tmp6.xyz * float3(2.0, 2.0, 2.0) + float3(1.0, 1.0, 1.0);
                tmp0.yzw = -tmp6.xyz * tmp0.yzw + float3(1.0, 1.0, 1.0);
                tmp4.xyz = tmp4.xyz * tmp5.xyz;
                tmp5.xyz = tmp5.xyz > float3(0.5, 0.5, 0.5);
                tmp4.xyz = tmp4.xyz + tmp4.xyz;
                tmp0.yzw = saturate(tmp5.xyz ? tmp0.yzw : tmp4.xyz);
                tmp1.xw = _NRMUV1.xx * tmp1.yz + inp.texcoord.xy;
                tmp1.yz = _OverrideUV1.xx * tmp1.yz + inp.texcoord.xy;
                tmp4 = tex2D(_Override, tmp1.yz);
                tmp1.yz = tmp1.xw * _PaintStrokes_ST.xy + _PaintStrokes_ST.zw;
                tmp1.xw = tmp1.xw * _Normal_ST.xy + _Normal_ST.zw;
                tmp5 = tex2D(_Normal, tmp1.xw);
                tmp1 = tex2D(_PaintStrokes, tmp1.yz);
                tmp0.yzw = tmp0.yzw - tmp1.xyz;
                tmp0.yzw = _PaintMaskTriplanar.xxx * tmp0.yzw + tmp1.xyz;
                tmp1.x = tmp0.y * 0.3 + 0.35;
                tmp0.yzw = tmp0.yzw - float3(0.5, 0.5, 0.5);
                tmp1.zw = inp.texcoord2.zx * _Normal_ST.xy + _Normal_ST.zw;
                tmp6 = tex2D(_Normal, tmp1.zw);
                tmp6.x = tmp6.w * tmp6.x;
                tmp6.xy = tmp6.xy * float2(2.0, 2.0) + float2(-1.0, -1.0);
                tmp1.z = dot(tmp6.xy, tmp6.xy);
                tmp1.z = min(tmp1.z, 1.0);
                tmp1.yz = float2(1.0, 1.0) - tmp1.xz;
                tmp6.z = sqrt(tmp1.z);
                tmp7 = inp.texcoord2.xyyz * _Normal_ST + _Normal_ST;
                tmp8 = tex2D(_Normal, tmp7.zw);
                tmp7 = tex2D(_Normal, tmp7.xy);
                tmp8.x = tmp8.w * tmp8.x;
                tmp8.xy = tmp8.xy * float2(2.0, 2.0) + float2(-1.0, -1.0);
                tmp1.z = dot(tmp8.xy, tmp8.xy);
                tmp1.z = min(tmp1.z, 1.0);
                tmp1.z = 1.0 - tmp1.z;
                tmp8.z = sqrt(tmp1.z);
                tmp7.x = tmp7.w * tmp7.x;
                tmp7.xy = tmp7.xy * float2(2.0, 2.0) + float2(-1.0, -1.0);
                tmp1.z = dot(tmp7.xy, tmp7.xy);
                tmp1.z = min(tmp1.z, 1.0);
                tmp1.z = 1.0 - tmp1.z;
                tmp7.z = sqrt(tmp1.z);
                tmp8.xyz = tmp8.xyz - tmp7.xyz;
                tmp8.xyz = abs(tmp3.yyy) * tmp8.xyz + tmp7.xyz;
                tmp6.xyz = tmp6.xyz - tmp8.xyz;
                tmp6.xyz = abs(tmp3.zzz) * tmp6.xyz + tmp8.xyz;
                tmp7.xyz = tmp7.xyz - tmp6.xyz;
                tmp6.xyz = abs(tmp3.www) * tmp7.xyz + tmp6.xyz;
                tmp5.x = tmp5.w * tmp5.x;
                tmp5.xy = tmp5.xy * float2(2.0, 2.0) + float2(-1.0, -1.0);
                tmp1.z = dot(tmp5.xy, tmp5.xy);
                tmp1.z = min(tmp1.z, 1.0);
                tmp1.z = 1.0 - tmp1.z;
                tmp5.z = sqrt(tmp1.z);
                tmp6.xyz = tmp6.xyz - tmp5.xyz;
                tmp5.xyz = _NRMTriplanar.xxx * tmp6.xyz + tmp5.xyz;
                tmp6.xyz = tmp5.yyy * inp.texcoord5.xyz;
                tmp5.xyw = tmp5.xxx * inp.texcoord4.xyz + tmp6.xyz;
                tmp3.xyz = tmp5.zzz * tmp3.yzw + tmp5.xyw;
                tmp1.z = dot(tmp3.xyz, tmp3.xyz);
                tmp1.z = rsqrt(tmp1.z);
                tmp3.xyz = tmp1.zzz * tmp3.xyz;
                tmp5.xyz = _WorldSpaceCameraPos - inp.texcoord2.xyz;
                tmp1.z = dot(tmp5.xyz, tmp5.xyz);
                tmp1.z = rsqrt(tmp1.z);
                tmp6.xyz = tmp1.zzz * tmp5.xyz;
                tmp1.w = dot(tmp3.xyz, tmp6.xyz);
                tmp1.w = max(tmp1.w, 0.0);
                tmp1.w = 1.0 - tmp1.w;
                tmp2.y = log(tmp1.w);
                tmp6 = _Color00 - _Color30;
                tmp7 = tex2D(_ColorMask, inp.texcoord.xy);
                tmp6 = tmp7.xxxx * tmp6 + _Color30;
                tmp8 = _Color10 - tmp6;
                tmp6 = tmp7.yyyy * tmp8 + tmp6;
                tmp8 = _Color20 - tmp6;
                tmp6 = tmp7.zzzz * tmp8 + tmp6;
                tmp8 = _Color40 - tmp6;
                tmp9.xyz = saturate(tmp7.xyz * float3(1.49925, 1.49925, 1.49925) + float3(-0.4992504, -0.4992504, -0.4992504));
                tmp2.w = tmp9.y * tmp9.x;
                tmp2.w = tmp9.z * tmp2.w;
                tmp9.xyz = tmp9.xxy * tmp9.zyz + -tmp2.www;
                tmp6 = tmp9.xxxx * tmp8 + tmp6;
                tmp8 = _Color50 - tmp6;
                tmp6 = tmp9.yyyy * tmp8 + tmp6;
                tmp8 = _Color60 - tmp6;
                tmp6 = tmp9.zzzz * tmp8 + tmp6;
                tmp8 = _Color70 - tmp6;
                tmp6 = tmp2.wwww * tmp8 + tmp6;
                tmp3.w = tmp6.x * 2.5 + 1.5;
                tmp2.y = tmp2.y * tmp3.w;
                tmp2.y = exp(tmp2.y);
                tmp2.y = tmp2.y * tmp2.y;
                tmp2.y = min(tmp2.y, 1.0);
                tmp3.w = tmp2.y - 0.5;
                tmp3.w = -tmp3.w * 2.0 + 1.0;
                tmp1.y = -tmp3.w * tmp1.y + 1.0;
                tmp1.x = dot(tmp1.xy, tmp2.xy);
                tmp2.y = tmp2.y > 0.5;
                tmp1.x = saturate(tmp2.y ? tmp1.y : tmp1.x);
                tmp1.y = saturate(tmp3.y);
                tmp1.y = abs(tmp3.x) + tmp1.y;
                tmp1.y = abs(tmp3.z) + tmp1.y;
                tmp1.x = tmp1.y * tmp1.x;
                tmp8.xyz = _WorldSpaceLightPos0.www * -inp.texcoord2.xyz + _WorldSpaceLightPos0.xyz;
                tmp1.y = dot(tmp8.xyz, tmp8.xyz);
                tmp1.y = rsqrt(tmp1.y);
                tmp8.xyz = tmp1.yyy * tmp8.xyz;
                tmp5.xyz = tmp5.xyz * tmp1.zzz + tmp8.xyz;
                tmp1.y = dot(tmp3.xyz, tmp8.xyz);
                tmp1.z = dot(tmp5.xyz, tmp5.xyz);
                tmp1.z = rsqrt(tmp1.z);
                tmp5.xyz = tmp1.zzz * tmp5.xyz;
                tmp1.z = dot(tmp5.xyz, tmp3.xyz);
                tmp1.z = max(tmp1.z, 0.0);
                tmp1.z = log(tmp1.z);
                tmp3 = _Color01 - _Color31;
                tmp3 = tmp7.xxxx * tmp3 + _Color31;
                tmp5 = _Color11 - tmp3;
                tmp3 = tmp7.yyyy * tmp5 + tmp3;
                tmp5 = _Color21 - tmp3;
                tmp3 = tmp7.zzzz * tmp5 + tmp3;
                tmp2.y = 1.0 - tmp7.w;
                tmp5 = _Color41 - tmp3;
                tmp3 = tmp9.xxxx * tmp5 + tmp3;
                tmp5 = _Color51 - tmp3;
                tmp3 = tmp9.yyyy * tmp5 + tmp3;
                tmp5 = _Color61 - tmp3;
                tmp3 = tmp9.zzzz * tmp5 + tmp3;
                tmp5 = _Color71 - tmp3;
                tmp3 = tmp2.wwww * tmp5 + tmp3;
                tmp5.xyz = tmp3.xxx * float3(8.0, 0.75, -0.1) + float3(-1.0, 0.25, 0.5);
                tmp2.w = exp(tmp5.x);
                tmp2.w = tmp1.z * tmp2.w;
                tmp1.z = tmp1.z * 64.0;
                tmp1.z = exp(tmp1.z);
                tmp2.w = exp(tmp2.w);
                tmp5.x = tmp3.x + tmp3.x;
                tmp5.x = saturate(tmp5.y * tmp5.x);
                tmp2.w = tmp2.w * tmp5.x;
                tmp5.xy = tmp3.xx * float2(0.75, 3.0);
                tmp2.w = saturate(tmp2.w * tmp5.y);
                tmp5.w = max(tmp1.y, 0.0);
                tmp7.xy = tmp5.ww * float2(1.666667, 20.0) + float2(-0.3333333, -3.0);
                tmp7.y = max(tmp7.y, 0.0);
                tmp7.x = saturate(tmp7.x);
                tmp7.y = min(tmp7.y, 0.8);
                tmp7.x = tmp7.y + tmp7.x;
                tmp5.w = tmp5.w * tmp2.w + tmp7.x;
                tmp7.xy = tmp3.xx + float2(1.0, 2.0);
                tmp5.w = tmp1.x * tmp7.x + tmp5.w;
                tmp1.x = tmp1.x * tmp7.x;
                tmp7.x = dot(inp.texcoord7.xyz, inp.texcoord7.xyz);
                tmp8 = tex2D(_LightTexture0, tmp7.xx);
                tmp1.x = tmp5.w * tmp8.x + tmp1.x;
                tmp7.xzw = tmp8.xxx * _LightColor0.xyz;
                tmp1.x = tmp2.x * tmp1.x;
                tmp5.w = dot(_LightColor0.xyz, float3(0.3, 0.59, 0.11));
                tmp8.x = -tmp1.x * tmp5.w + tmp2.x;
                tmp1.x = tmp1.x * tmp5.w;
                tmp1.x = tmp6.x * tmp8.x + tmp1.x;
                tmp5.w = tmp2.x * 0.5 + tmp2.w;
                tmp5.w = tmp5.w - tmp1.x;
                tmp5.w = tmp6.x * tmp5.w + tmp1.x;
                tmp1.x = saturate(tmp1.x);
                tmp8.xy = tmp5.ww * float2(5.0, 2.666667);
                tmp8.xy = saturate(tmp8.xy);
                tmp8.zw = saturate(tmp5.ww * float2(-1.111111, -2.181818) + float2(1.111111, 1.2));
                tmp5.w = log(tmp5.w);
                tmp8.xy = tmp8.zw * tmp8.xy;
                tmp5.xy = tmp5.yx * tmp8.yx;
                tmp5.x = saturate(tmp5.x);
                tmp5.y = log(tmp5.y);
                tmp5.y = tmp5.y * tmp7.y;
                tmp5.y = exp(tmp5.y);
                tmp7.y = tmp3.x * 2.0 + 1.0;
                tmp5.w = tmp5.w * tmp7.y;
                tmp5.w = exp(tmp5.w);
                tmp5.yw = min(tmp5.yw, float2(1.0, 1.0));
                tmp5.x = tmp5.w - tmp5.x;
                tmp5.x = max(tmp5.x, 0.0);
                tmp5.x = tmp5.y + tmp5.x;
                tmp5.x = min(tmp5.x, 1.0);
                tmp8.xy = tmp5.xx * float2(1.49925, 3.003003);
                tmp8.xy = min(tmp8.xy, float2(1.0, 1.0));
                tmp3.yzw = tmp3.yzw - tmp6.yzw;
                tmp3.yzw = tmp1.xxx * tmp3.yzw + tmp6.yzw;
                tmp1.x = saturate(tmp2.y + tmp6.x);
                tmp4.xyz = tmp4.xyz - tmp3.yzw;
                tmp3.yzw = tmp4.www * tmp4.xyz + tmp3.yzw;
                tmp4.xy = tmp3.wz;
                tmp6.xy = tmp3.zw - tmp4.xy;
                tmp5.w = tmp4.y >= tmp3.w;
                tmp5.w = tmp5.w ? 1.0 : 0.0;
                tmp4.zw = float2(-1.0, 0.6666667);
                tmp6.zw = float2(1.0, -1.0);
                tmp4 = tmp5.wwww * tmp6.xywz + tmp4.xywz;
                tmp5.w = tmp3.y >= tmp4.x;
                tmp5.w = tmp5.w ? 1.0 : 0.0;
                tmp6.z = tmp4.w;
                tmp4.w = tmp3.y;
                tmp6.xyw = tmp4.wyx;
                tmp6 = tmp6 - tmp4;
                tmp4 = tmp5.wwww * tmp6 + tmp4;
                tmp5.w = min(tmp4.y, tmp4.w);
                tmp5.w = tmp4.x - tmp5.w;
                tmp6.x = tmp5.w * 6.0 + 0.0;
                tmp4.y = tmp4.w - tmp4.y;
                tmp4.y = tmp4.y / tmp6.x;
                tmp4.y = tmp4.y + tmp4.z;
                tmp6.xyz = abs(tmp4.yyy) + float3(-0.05, -0.3833334, 0.2833333);
                tmp4.yzw = abs(tmp4.yyy) + float3(0.01, -0.3233334, 0.3433333);
                tmp4.yzw = frac(tmp4.yzw);
                tmp4.yzw = -tmp4.yzw * float3(2.0, 2.0, 2.0) + float3(1.0, 1.0, 1.0);
                tmp4.yzw = saturate(abs(tmp4.yzw) * float3(3.0, 3.0, 3.0) + float3(-1.0, -1.0, -1.0));
                tmp4.yzw = tmp4.yzw - float3(1.0, 1.0, 1.0);
                tmp6.xyz = frac(tmp6.xyz);
                tmp6.xyz = -tmp6.xyz * float3(2.0, 2.0, 2.0) + float3(1.0, 1.0, 1.0);
                tmp6.xyz = saturate(abs(tmp6.xyz) * float3(3.0, 3.0, 3.0) + float3(-1.0, -1.0, -1.0));
                tmp6.xyz = tmp6.xyz - float3(1.0, 1.0, 1.0);
                tmp6.w = tmp4.x + 0.0;
                tmp5.w = tmp5.w / tmp6.w;
                tmp6.xyz = tmp5.www * tmp6.xyz + float3(1.0, 1.0, 1.0);
                tmp4.yzw = tmp5.www * tmp4.yzw + float3(1.0, 1.0, 1.0);
                tmp9.xyz = tmp4.xxx * tmp6.xyz;
                tmp5.w = dot(tmp9.xyz, float3(0.3, 0.59, 0.11));
                tmp10.xyz = -tmp6.xyz * tmp4.xxx + tmp5.www;
                tmp6.xyz = tmp6.xyz * tmp4.xxx + -tmp10.xyz;
                tmp9.xyz = tmp10.xyz * float3(0.2, 0.2, 0.2) + tmp9.xyz;
                tmp10.xyz = -tmp6.xyz * tmp5.zzz + tmp3.yzw;
                tmp6.xyz = tmp5.zzz * tmp6.xyz;
                tmp8.xzw = tmp8.xxx * tmp10.xyz + tmp6.xyz;
                tmp10.xyz = tmp3.xxx * float3(1.6, -0.1, 0.3) + float3(-0.8, 0.6, 1.2);
                tmp8.xzw = -tmp9.xyz * tmp10.yyy + tmp8.xzw;
                tmp9.xyz = tmp9.xyz * tmp10.yyy;
                tmp8.xyz = tmp8.yyy * tmp8.xzw + tmp9.xyz;
                tmp9.xyz = tmp4.xxx * tmp4.yzw;
                tmp5.z = dot(tmp9.xyz, float3(0.3, 0.59, 0.11));
                tmp4.xyz = -tmp4.yzw * tmp4.xxx + tmp5.zzz;
                tmp4.xyz = tmp4.xyz * float3(0.05, 0.05, 0.05) + tmp9.xyz;
                tmp4.xyz = saturate(tmp10.zzz * tmp4.xyz);
                tmp10.x = saturate(tmp10.x);
                tmp4.xyz = tmp4.xyz - tmp3.yzw;
                tmp4.w = tmp5.x * 1.49925 + -0.4992504;
                tmp4.w = max(tmp4.w, 0.0);
                tmp3.yzw = tmp4.www * tmp4.xyz + tmp3.yzw;
                tmp3.yzw = tmp3.yzw - tmp8.xyz;
                tmp3.yzw = tmp5.xxx * tmp3.yzw + tmp8.xyz;
                tmp4.x = tmp3.z >= tmp3.w;
                tmp4.x = tmp4.x ? 1.0 : 0.0;
                tmp8.xy = tmp3.wz;
                tmp9.xy = tmp3.zw - tmp8.xy;
                tmp8.zw = float2(-1.0, 0.6666667);
                tmp9.zw = float2(1.0, -1.0);
                tmp4 = tmp4.xxxx * tmp9.xywz + tmp8.xywz;
                tmp5.x = tmp3.y >= tmp4.x;
                tmp5.x = tmp5.x ? 1.0 : 0.0;
                tmp8.z = tmp4.w;
                tmp4.w = tmp3.y;
                tmp8.xyw = tmp4.wyx;
                tmp8 = tmp8 - tmp4;
                tmp4 = tmp5.xxxx * tmp8 + tmp4;
                tmp5.x = min(tmp4.y, tmp4.w);
                tmp5.x = tmp4.x - tmp5.x;
                tmp5.z = tmp5.x * 6.0 + 0.0;
                tmp4.y = tmp4.w - tmp4.y;
                tmp4.y = tmp4.y / tmp5.z;
                tmp4.y = tmp4.y + tmp4.z;
                tmp4.yzw = abs(tmp4.yyy) + float3(-0.125, -0.4583333, 0.2083333);
                tmp4.yzw = frac(tmp4.yzw);
                tmp4.yzw = -tmp4.yzw * float3(2.0, 2.0, 2.0) + float3(1.0, 1.0, 1.0);
                tmp4.yzw = saturate(abs(tmp4.yzw) * float3(3.0, 3.0, 3.0) + float3(-1.0, -1.0, -1.0));
                tmp4.yzw = tmp4.yzw - float3(1.0, 1.0, 1.0);
                tmp5.z = tmp4.x + 0.0;
                tmp5.x = tmp5.x / tmp5.z;
                tmp4.yzw = tmp5.xxx * tmp4.yzw + float3(1.0, 1.0, 1.0);
                tmp5.xzw = tmp4.xxx * tmp4.yzw;
                tmp6.w = dot(tmp5.xyz, float3(0.3, 0.59, 0.11));
                tmp4.xyz = -tmp4.yzw * tmp4.xxx + tmp6.www;
                tmp4.xyz = tmp4.xyz * float3(0.1, 0.1, 0.1) + tmp5.xzw;
                tmp4.xyz = tmp4.xyz - tmp3.yzw;
                tmp3.yzw = tmp5.yyy * tmp4.xyz + tmp3.yzw;
                tmp4.xyz = tmp3.yzw * float3(1.333, 1.333, 1.333);
                tmp4.w = dot(tmp4.xyz, float3(0.3, 0.59, 0.11));
                tmp3.yzw = -tmp3.yzw * float3(1.333, 1.333, 1.333) + tmp4.www;
                tmp3.yzw = tmp3.yzw * tmp10.xxx;
                tmp3.yzw = tmp2.www * tmp3.yzw + tmp4.xyz;
                tmp2.w = tmp3.z >= tmp3.w;
                tmp2.w = tmp2.w ? 1.0 : 0.0;
                tmp4.xy = tmp3.wz;
                tmp5.xy = tmp3.zw - tmp4.xy;
                tmp4.zw = float2(-1.0, 0.6666667);
                tmp5.zw = float2(1.0, -1.0);
                tmp4 = tmp2.wwww * tmp5.xywz + tmp4.xywz;
                tmp2.w = tmp3.y >= tmp4.x;
                tmp2.w = tmp2.w ? 1.0 : 0.0;
                tmp5.z = tmp4.w;
                tmp4.w = tmp3.y;
                tmp5.xyw = tmp4.wyx;
                tmp5 = tmp5 - tmp4;
                tmp4 = tmp2.wwww * tmp5 + tmp4;
                tmp2.w = min(tmp4.y, tmp4.w);
                tmp2.w = tmp4.x - tmp2.w;
                tmp5.x = tmp2.w * 6.0 + 0.0;
                tmp4.y = tmp4.w - tmp4.y;
                tmp4.y = tmp4.y / tmp5.x;
                tmp4.y = tmp4.y + tmp4.z;
                tmp4.xz = tmp4.xx + float2(0.0, 0.1);
                tmp5.xyz = abs(tmp4.yyy) + float3(0.0, -0.3333333, 0.3333333);
                tmp5.xyz = frac(tmp5.xyz);
                tmp5.xyz = -tmp5.xyz * float3(2.0, 2.0, 2.0) + float3(1.0, 1.0, 1.0);
                tmp5.xyz = saturate(abs(tmp5.xyz) * float3(3.0, 3.0, 3.0) + float3(-1.0, -1.0, -1.0));
                tmp5.xyz = tmp5.xyz - float3(1.0, 1.0, 1.0);
                tmp2.w = tmp2.w / tmp4.x;
                tmp2.w = tmp2.w - 0.5;
                tmp4.xyw = tmp2.www * tmp5.xyz + float3(1.0, 1.0, 1.0);
                tmp4.xyz = tmp4.xyw * tmp4.zzz + -tmp3.yzw;
                tmp3.yzw = saturate(tmp2.zzz * tmp4.xyz + tmp3.yzw);
                tmp2.z = _Time.y * 6.283;
                tmp2.z = sin(tmp2.z);
                tmp2.zw = tmp2.zz * float2(0.35, 0.05) + float2(0.85, 0.95);
                tmp2.w = tmp2.w - tmp2.z;
                tmp4.x = _SpiralColor * 2.0 + -1.0;
                tmp2.z = abs(tmp4.x) * tmp2.w + tmp2.z;
                tmp4.x = tmp2.x * tmp2.z;
                tmp2.x = _GlowSpeed * _Time.y;
                tmp5.y = frac(tmp2.x);
                tmp5.xzw = float3(0.0, 1.0, -1.0);
                tmp4.y = _SpiralColor;
                tmp2.xz = tmp4.xy + tmp5.xy;
                tmp2.xz = tmp2.xz * _GlowRamp_ST.xy + _GlowRamp_ST.zw;
                tmp4 = tex2D(_GlowRamp, tmp2.xz);
                tmp2.x = tmp2.y * _GlowMultiplier;
                tmp2.x = tmp2.x * 3.0;
                tmp2.xzw = tmp4.xyz * tmp2.xxx + -tmp3.yzw;
                tmp2.xyw = tmp2.yyy * tmp2.zwx + tmp3.zwy;
                tmp3.y = tmp2.x >= tmp2.y;
                tmp3.y = tmp3.y ? 1.0 : 0.0;
                tmp4.xy = tmp2.yx;
                tmp5.xy = tmp2.xy - tmp4.xy;
                tmp4.zw = float2(-1.0, 0.6666667);
                tmp4 = tmp3.yyyy * tmp5 + tmp4;
                tmp3.y = tmp2.w >= tmp4.x;
                tmp3.y = tmp3.y ? 1.0 : 0.0;
                tmp2.xyz = tmp4.xyw;
                tmp4.xyw = tmp2.wyx;
                tmp4 = tmp4 - tmp2;
                tmp2 = tmp3.yyyy * tmp4 + tmp2;
                tmp3.y = min(tmp2.y, tmp2.w);
                tmp3.y = tmp2.x - tmp3.y;
                tmp3.z = tmp3.y * 6.0 + 0.0;
                tmp2.y = tmp2.w - tmp2.y;
                tmp2.y = tmp2.y / tmp3.z;
                tmp2.y = tmp2.y + tmp2.z;
                tmp0.y = tmp0.y * 0.04 + abs(tmp2.y);
                tmp2.yzw = tmp0.yyy + float3(0.0, -0.3333333, 0.3333333);
                tmp2.yzw = frac(tmp2.yzw);
                tmp2.yzw = -tmp2.yzw * float3(2.0, 2.0, 2.0) + float3(1.0, 1.0, 1.0);
                tmp2.yzw = saturate(abs(tmp2.yzw) * float3(3.0, 3.0, 3.0) + float3(-1.0, -1.0, -1.0));
                tmp2.yzw = tmp2.yzw - float3(1.0, 1.0, 1.0);
                tmp0.y = tmp2.x + 0.0;
                tmp0.w = tmp0.w * 0.075 + tmp2.x;
                tmp0.y = tmp3.y / tmp0.y;
                tmp0.y = tmp0.z * 0.05 + tmp0.y;
                tmp2.xyz = tmp0.yyy * tmp2.yzw + float3(1.0, 1.0, 1.0);
                tmp0.yzw = tmp0.www * tmp2.xyz;
                tmp0.yzw = tmp1.xxx * -tmp0.yzw + tmp0.yzw;
                tmp1.x = tmp0.x * 2.0 + -1.0;
                tmp1.x = tmp1.w * tmp1.w + tmp1.x;
                tmp2.xyz = tmp1.xxx * float3(0.7768763, 0.0, -0.4042597) + float3(0.0, 1.0, 0.6689656);
                tmp2.xyz = tmp2.xyz - tmp0.yzw;
                tmp0.xyz = tmp0.xxx * tmp2.xyz + tmp0.yzw;
                tmp1.xzw = tmp1.zzz * tmp7.xzw;
                tmp1.xzw = tmp3.xxx * tmp1.xzw;
                tmp2.xyz = tmp6.xyz * float3(0.5, 0.5, 0.5);
                tmp3.xyz = -tmp6.xyz * float3(0.5, 0.5, 0.5) + float3(1.0, 1.0, 1.0);
                tmp2.xyz = tmp1.yyy * tmp3.xyz + tmp2.xyz;
                tmp2.xyz = max(tmp2.xyz, float3(0.0, 0.0, 0.0));
                tmp2.xyz = tmp7.xzw * tmp2.xyz;
                o.sv_target.xyz = tmp2.xyz * tmp0.xyz + tmp1.xzw;
                o.sv_target.w = 0.0;
                return o;
			}
			ENDCG
		}
	}
	Fallback "Diffuse"
	CustomEditor "ShaderForgeMaterialInspector"
}